import type { TableColumn } from "./table-utils";
import { PURCHASE_CURRENCY_OPTIONS } from "./purchase-order-form";

export type FieldType = "text" | "number" | "date" | "datetime" | "boolean" | "textarea" | "select" | "lineType";

export type EntityField = TableColumn & {
  type?: FieldType;
  placeholder?: string;
  required?: boolean;
  readonly?: boolean;
  options?: Array<{ label: string; value: string }>;
};

export type EntityConfig = {
  key: string;
  title: string;
  table: string;
  primaryKey: string;
  uniqueKeys?: string[];
  navGroup: string;
  route: string;
  description: string;
  listFields: EntityField[];
  formFields: EntityField[];
  filters: EntityField[];
  defaultSort?: string;
};

export type NavGroup = {
  title: string;
  items: EntityConfig[];
  children?: Array<{
    title: string;
    items: EntityConfig[];
  }>;
};

export const entityConfigs: EntityConfig[] = [
  {
    key: "countries",
    title: "国家管理",
    table: "countries",
    primaryKey: "code",
    navGroup: "基础信息",
    route: "/master-data/countries",
    description: "维护国家代码及中英文名称。",
    filters: [{ key: "keyword", label: "国家", placeholder: "请输入国家代码或名称" }],
    listFields: [
      { key: "code", label: "国家代码" },
      { key: "nameZh", label: "国家中文名" },
      { key: "nameEn", label: "国家英文名" },
      { key: "nameLocal", label: "当地语言名称" },
    ],
    formFields: [
      { key: "code", label: "国家代码", required: true },
      { key: "nameZh", label: "国家中文名", required: true },
      { key: "nameEn", label: "国家英文名" },
      { key: "nameLocal", label: "当地语言名称" },
    ],
  },
  {
    key: "delivery-locations",
    title: "交付地址",
    table: "deliverylocations",
    primaryKey: "locationId",
    navGroup: "基础信息",
    route: "/master-data/delivery-locations",
    description: "维护仓库、办公室、机房、Broker 等交付站点。",
    filters: [
      { key: "keyword", label: "地点", placeholder: "请输入地点ID或名称" },
      { key: "countryCode", label: "国家", placeholder: "请选择国家" },
    ],
    listFields: [
      { key: "locationId", label: "地点ID" },
      { key: "countryCode", label: "国家" },
      { key: "locationType", label: "地点类型" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
      { key: "fullAddress", label: "详细地址" },
    ],
    formFields: [
      { key: "locationId", label: "地点ID", required: true },
      { key: "countryCode", label: "国家代码", required: true },
      { key: "locationType", label: "地点类型", required: true },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
      { key: "fullAddress", label: "详细地址", type: "textarea" },
    ],
  },
  {
    key: "delivery-contacts",
    title: "收件人信息",
    table: "deliverycontacts",
    primaryKey: "contactId",
    navGroup: "基础信息",
    route: "/master-data/delivery-contacts",
    description: "维护交付地址对应的联系人、电话和邮箱。",
    filters: [{ key: "keyword", label: "联系人", placeholder: "请输入姓名、电话或邮箱" }],
    listFields: [
      { key: "contactId", label: "联系人ID" },
      { key: "locationId", label: "所属地点" },
      { key: "name", label: "姓名" },
      { key: "phone", label: "电话" },
      { key: "email", label: "邮箱" },
    ],
    formFields: [
      { key: "contactId", label: "联系人ID", required: true },
      { key: "locationId", label: "所属地点ID", required: true },
      { key: "name", label: "姓名", required: true },
      { key: "phone", label: "电话" },
      { key: "email", label: "邮箱" },
    ],
  },
  {
    key: "datacenters",
    title: "机房管理",
    table: "datacenters",
    primaryKey: "dcCode",
    navGroup: "基础信息",
    route: "/master-data/datacenters",
    description: "维护机房与物理交付地址的绑定关系。",
    filters: [{ key: "keyword", label: "机房", placeholder: "请输入机房ID或名称" }],
    listFields: [
      { key: "dcCode", label: "机房ID" },
      { key: "locationId", label: "物理地址" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
    ],
    formFields: [
      { key: "dcCode", label: "机房ID", required: true },
      { key: "locationId", label: "物理地址ID", required: true },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
    ],
  },
  {
    key: "suppliers",
    title: "供应商管理",
    table: "suppliers",
    primaryKey: "supplierId",
    navGroup: "基础信息",
    route: "/master-data/suppliers",
    description: "维护 ODM 供应商信息。",
    filters: [{ key: "keyword", label: "供应商", placeholder: "请输入供应商代码或名称" }],
    listFields: [
      { key: "supplierId", label: "供应商ID" },
      { key: "supplierCode", label: "供应商代码" },
      { key: "name", label: "名称" },
    ],
    formFields: [
      { key: "supplierId", label: "供应商ID", required: true },
      { key: "supplierCode", label: "供应商代码", required: true },
      { key: "name", label: "名称", required: true },
    ],
  },
  {
    key: "instance-models",
    title: "实例型号",
    table: "instancemodels",
    primaryKey: "deviceCode",
    navGroup: "基础信息",
    route: "/master-data/instance-models",
    description: "维护设备编码、机型和实例型号名称。",
    filters: [
      { key: "keyword", label: "实例型号", placeholder: "请输入设备编码、机型或名称" },
    ],
    listFields: [
      { key: "deviceCode", label: "设备编码" },
      { key: "modelCode", label: "机型" },
      { key: "xxllCode", label: "xxll编码" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
    ],
    formFields: [
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "modelCode", label: "机型", required: true },
      { key: "xxllCode", label: "xxll编码" },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
    ],
  },
  {
    key: "instance-contracts",
    title: "实例合同",
    table: "instancecontracts",
    primaryKey: "id",
    uniqueKeys: ["contractNo", "countryCode", "deviceCode"],
    navGroup: "合同管理",
    route: "/contracts/instance-contracts",
    description: "维护实例合同、国家、实例型号与分阶段含税单价。",
    filters: [
      { key: "keyword", label: "实例合同", placeholder: "请输入合同号、国家、设备编码或机型" },
    ],
    listFields: [
      { key: "id", label: "内部ID", defaultVisible: false },
      { key: "contractNo", label: "合同号" },
      { key: "countryCode", label: "国家" },
      { key: "deviceCode", label: "设备编码" },
      { key: "modelCode", label: "机型" },
      { key: "instanceModelEn", label: "实例型号（英文）" },
      { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "first24MonthPriceUSD", label: "前24个月含税单价", type: "number" },
      { key: "next36MonthPriceUSD", label: "后36个月含税单价", type: "number" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "contractNo", label: "合同号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "modelCode", label: "机型", required: true },
      { key: "instanceModelEn", label: "实例型号（英文）", required: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "first24MonthPriceUSD", label: "前24个月含税单价", type: "number", required: true },
      { key: "next36MonthPriceUSD", label: "后36个月含税单价", type: "number", required: true },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "requests",
    title: "需求单",
    table: "requests",
    primaryKey: "requestNo",
    navGroup: "客户需求",
    route: "/requests/orders",
    description: "以主从表单维护客户需求单和需求明细。",
    filters: [
      { key: "keyword", label: "需求单", placeholder: "请输入需求单号、合同号或批次" },
      { key: "status", label: "状态", placeholder: "请选择状态" },
    ],
    listFields: [
      { key: "requestNo", label: "需求单号" },
      { key: "countryCode", label: "国家" },
      { key: "contractNo", label: "合同号" },
      { key: "batchName", label: "批次名称" },
      { key: "requestType", label: "类型" },
      { key: "status", label: "状态" },
      { key: "plannedDeliveryDate", label: "计划交付日期", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "requestNo", label: "需求单号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "contractNo", label: "合同号", required: true },
      { key: "batchName", label: "批次名称", required: true },
      { key: "requestType", label: "类型", required: true },
      { key: "status", label: "状态", required: true },
      { key: "plannedDeliveryDate", label: "计划交付日期", type: "date" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "request-items",
    title: "需求明细一览",
    table: "requestitems",
    primaryKey: "id",
    navGroup: "客户需求",
    route: "/requests/items",
    description: "跨批次集中查看所有需求明细。",
    filters: [
      { key: "keyword", label: "需求明细", placeholder: "请输入需求单号、设备编码或供应商" },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "requestNo", label: "需求单号" },
      { key: "deviceCode", label: "设备编码" },
      { key: "supplierId", label: "供应商" },
      { key: "requestedAt", label: "需求时间", type: "date" },
      { key: "quantity", label: "节点数量", type: "number" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "requestNo", label: "需求单号", required: true },
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "supplierId", label: "供应商ID", required: true },
      { key: "requestedAt", label: "需求时间", type: "date" },
      { key: "quantity", label: "节点数量", type: "number", required: true },
    ],
  },
  {
    key: "purchase-orders",
    title: "采购订单",
    table: "purchaseorders",
    primaryKey: "poNo",
    navGroup: "采购管理",
    route: "/purchase/orders",
    description: "以主从表单维护 PO 主单和采购明细。",
    filters: [{ key: "keyword", label: "采购订单", placeholder: "请输入PO订单号或币种" }],
    listFields: [
      { key: "poNo", label: "PO订单号" },
      { key: "requestNo", label: "来源需求单号" },
      { key: "status", label: "采购状态" },
      { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "releasedAt", label: "下发日期", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
    ],
    formFields: [
      { key: "poNo", label: "PO订单号", required: true },
      { key: "requestNo", label: "来源需求单号" },
      { key: "status", label: "采购状态", required: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "releasedAt", label: "下发日期", type: "date" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "purchase-order-items",
    title: "采购明细一览",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "采购管理",
    route: "/purchase/items",
    description: "集中查看所有 PO 采购明细。",
    filters: [{ key: "keyword", label: "采购明细", placeholder: "请输入PO订单号或需求明细ID" }],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "poNo", label: "PO订单号" },
      { key: "requestItemId", label: "需求明细" },
      { key: "unitPrice", label: "单价", type: "number" },
      { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
      { key: "softwareCoefficient", label: "软件系数", type: "number" },
      { key: "totalCoefficient", label: "总系数", type: "number" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "poNo", label: "PO订单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "unitPrice", label: "单价", type: "number" },
      { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
      { key: "softwareCoefficient", label: "软件系数", type: "number" },
      { key: "totalCoefficient", label: "总系数", type: "number" },
    ],
  },
  {
    key: "shipments",
    title: "物流列表",
    table: "shipments",
    primaryKey: "shipmentId",
    navGroup: "物流管理",
    route: "/shipments",
    description: "管理 PO 发运、交付快照和物流时间线。",
    defaultSort: "createdAt DESC",
    filters: [
      { key: "keyword", label: "物流", placeholder: "请输入物流ID、PO订单号或收件人" },
      { key: "transportMode", label: "运输方式", placeholder: "请选择运输方式" },
    ],
    listFields: [
      { key: "shipmentId", label: "物流ID" },
      { key: "poNo", label: "PO订单号" },
      { key: "purchaseOrderItemId", label: "采购明细ID" },
      { key: "deviceCode", label: "实例编码" },
      { key: "nameEn", label: "实例名称（英文）" },
      { key: "destinationLocationId", label: "目的地点" },
      { key: "recipientContactId", label: "收件人" },
      { key: "snapshotDestinationAddress", label: "交付地址快照", defaultVisible: false },
      { key: "snapshotRecipientName", label: "收件人快照", defaultVisible: false },
      { key: "snapshotRecipientPhone", label: "收件电话快照", defaultVisible: false },
      { key: "transportMode", label: "运输方式" },
      { key: "isReceived", label: "是否签收", type: "boolean" },
      { key: "crd", label: "CRD", type: "date" },
      { key: "apdAt", label: "APD交单", type: "date" },
      { key: "pickupAt", label: "ASD提货", type: "date" },
      { key: "departedAt", label: "起飞/开船", type: "date" },
      { key: "arrivedAt", label: "到港", type: "date" },
      { key: "customsClearedAt", label: "清关完成", type: "date" },
      { key: "deliveredAt", label: "派送", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime", defaultVisible: false },
      { key: "updatedAt", label: "更新时间", type: "datetime", defaultVisible: false },
    ],
    formFields: [
      { key: "shipmentId", label: "物流ID", required: true },
      { key: "poNo", label: "PO订单号", required: true },
      { key: "purchaseOrderItemId", label: "采购明细ID" },
      { key: "deviceCode", label: "实例编码" },
      { key: "nameEn", label: "实例名称（英文）" },
      { key: "destinationLocationId", label: "目的地点ID", required: true },
      { key: "recipientContactId", label: "收件联系人ID", required: true },
      { key: "snapshotDestinationAddress", label: "交付地址快照", type: "textarea", required: true },
      { key: "snapshotRecipientName", label: "收件人快照", required: true },
      { key: "snapshotRecipientPhone", label: "收件电话快照", required: true },
      { key: "transportMode", label: "运输方式" },
      { key: "isReceived", label: "是否签收", type: "boolean" },
      { key: "crd", label: "CRD", type: "date" },
      { key: "apdAt", label: "APD交单", type: "date" },
      { key: "pickupAt", label: "ASD提货", type: "date" },
      { key: "departedAt", label: "起飞/开船", type: "date" },
      { key: "arrivedAt", label: "到港", type: "date" },
      { key: "customsClearedAt", label: "清关完成", type: "date" },
      { key: "deliveredAt", label: "派送", type: "date" },
    ],
  },
  {
    key: "billing-available",
    title: "待生成月账单实例",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/billing-available",
    description: "从已确认下单且尚未生成月账单台账的实例中生成60个月账单。",
    filters: [{ key: "keyword", label: "待生成月账单", placeholder: "请输入国家、批次、需求单、PO或实例编码" }],
    listFields: [
      { key: "id", label: "采购明细ID" },
      { key: "poNo", label: "PO单号" },
      { key: "requestItemId", label: "需求明细ID" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
    formFields: [
      { key: "id", label: "采购明细ID", required: true },
      { key: "poNo", label: "PO单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
  },
  {
    key: "billing-ledgers",
    title: "月账单台账",
    table: "billinginstanceledgers",
    primaryKey: "ledgerId",
    navGroup: "财务管理",
    route: "/finance/billing-ledgers",
    description: "查看已确认月账单实例的合同价格锁定信息。",
    filters: [{ key: "keyword", label: "月账单台账", placeholder: "请输入国家、批次、需求单、PO或实例编码" }],
    listFields: [
      { key: "ledgerId", label: "台账ID" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "contractCurrency", label: "合同币种" },
      { key: "first24MonthPrice", label: "前24个月合同价", type: "number" },
      { key: "next36MonthPrice", label: "后36个月合同价", type: "number" },
      { key: "startMonth", label: "起始核销月份", type: "date" },
      { key: "status", label: "状态" },
    ],
    formFields: [
      { key: "ledgerId", label: "台账ID", required: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "actualCurrency", label: "实际币种" },
      { key: "actualUnitPrice", label: "实际单价", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "contractCurrency", label: "合同币种" },
      { key: "first24MonthPrice", label: "前24个月合同价", type: "number" },
      { key: "next36MonthPrice", label: "后36个月合同价", type: "number" },
      { key: "startMonth", label: "起始核销月份", type: "date" },
      { key: "status", label: "状态" },
    ],
    defaultSort: "confirmedAt DESC",
  },
  {
    key: "monthly-billing-writeoffs",
    title: "月账单每月核销明细",
    table: "monthlybillingwriteoffs",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/monthly-billing-writeoffs",
    description: "查看月账单台账生成的60个月实例核销明细。",
    filters: [{ key: "keyword", label: "月账单明细", placeholder: "请输入国家、批次、需求单、PO或实例编码" }],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "currency", label: "币种" },
      { key: "monthlyAmount", label: "月核销金额", type: "number" },
      { key: "monthlyTotalAmount", label: "月账单核销总金额", type: "number" },
      { key: "stage", label: "阶段" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "ledgerId", label: "台账ID", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "monthIndex", label: "月份序号", type: "number" },
      { key: "stage", label: "阶段" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "currency", label: "币种" },
      { key: "monthlyAmount", label: "月核销金额", type: "number" },
      { key: "monthlyTotalAmount", label: "月账单核销总金额", type: "number" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "billing-adjustments",
    title: "实例合同调整单",
    table: "billingadjustments",
    primaryKey: "adjustmentNo",
    navGroup: "合同管理",
    route: "/finance/billing-adjustments",
    description: "维护特定批次、特定实例在某个生效月份之后的月账单价格调整。",
    filters: [{ key: "keyword", label: "调整单", placeholder: "请输入调整单号、国家、批次或实例编码" }],
    listFields: [
      { key: "adjustmentNo", label: "调整单号" },
      { key: "status", label: "状态" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "currency", label: "币种" },
      { key: "effectiveMonth", label: "生效月份", type: "date" },
      { key: "adjustedFirst24MonthPrice", label: "调整后前24个月价", type: "number" },
      { key: "adjustedNext36MonthPrice", label: "调整后后36个月价", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    formFields: [
      { key: "adjustmentNo", label: "调整单号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "batchName", label: "批次号", required: true },
      { key: "deviceCode", label: "实例编码", required: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "effectiveMonth", label: "生效月份", type: "date", required: true },
      { key: "adjustedFirst24MonthPrice", label: "调整后前24个月价", type: "number", required: true },
      { key: "adjustedNext36MonthPrice", label: "调整后后36个月价", type: "number", required: true },
      { key: "reason", label: "调整原因", type: "textarea" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "service-fees",
    title: "服务费核算",
    table: "servicefeesnapshotitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/service-fees",
    description: "按月度月账单核销总额减预付款核销金额，实时核算服务费并可确认生成快照。",
    filters: [{ key: "keyword", label: "服务费核算", placeholder: "请输入国家、批次、需求单、PO或实例编码" }],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单核销总额", type: "number" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额", type: "number" },
      { key: "serviceFeeAmount", label: "月度服务费", type: "number" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单核销总额", type: "number" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额", type: "number" },
      { key: "serviceFeeAmount", label: "月度服务费", type: "number" },
      { key: "billingSourceIds", label: "月账单来源ID" },
      { key: "prepaymentSourceIds", label: "预付款来源ID" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
  },
  {
    key: "service-fee-snapshots",
    title: "服务费核算快照",
    table: "servicefeesnapshots",
    primaryKey: "snapshotNo",
    navGroup: "财务管理",
    route: "/finance/service-fee-snapshots",
    description: "查看已确认保存的服务费核算结果。",
    filters: [
      { key: "keyword", label: "快照", placeholder: "请输入快照编号、国家或批次" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
      { key: "batchName", label: "批次", placeholder: "批次" },
    ],
    listFields: [
      { key: "snapshotNo", label: "快照编号" },
      { key: "status", label: "状态" },
      { key: "startMonth", label: "开始月份", type: "date" },
      { key: "endMonth", label: "结束月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "billingTotal", label: "月账单合计", type: "number" },
      { key: "prepaymentTotal", label: "预付款合计", type: "number" },
      { key: "serviceFeeTotal", label: "服务费合计", type: "number" },
      { key: "instanceServiceFeeTotal", label: "实例服务费合计", type: "number" },
      { key: "feeServiceFeeTotal", label: "非实例费用合计", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    formFields: [
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "status", label: "状态" },
      { key: "startMonth", label: "开始月份", type: "date" },
      { key: "endMonth", label: "结束月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "keyword", label: "关键字" },
      { key: "billingTotal", label: "月账单合计", type: "number" },
      { key: "prepaymentTotal", label: "预付款合计", type: "number" },
      { key: "serviceFeeTotal", label: "服务费合计", type: "number" },
      { key: "instanceServiceFeeTotal", label: "实例服务费合计", type: "number" },
      { key: "feeServiceFeeTotal", label: "非实例费用合计", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    defaultSort: "confirmedAt DESC",
  },
  {
    key: "service-fee-snapshot-items",
    title: "服务费核算快照明细",
    table: "servicefeesnapshotitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/service-fee-snapshot-items",
    description: "查看已确认服务费核算快照中的明细行。",
    filters: [
      { key: "keyword", label: "快照明细", placeholder: "请输入快照编号、批次、需求单、PO或实例编码" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
      { key: "batchName", label: "批次", placeholder: "批次" },
    ],
    listFields: [
      { key: "snapshotNo", label: "快照编号" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单核销总额", type: "number" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额", type: "number" },
      { key: "serviceFeeAmount", label: "月度服务费", type: "number" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单核销总额", type: "number" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额", type: "number" },
      { key: "serviceFeeAmount", label: "月度服务费", type: "number" },
      { key: "billingSourceIds", label: "月账单来源ID" },
      { key: "prepaymentSourceIds", label: "预付款来源ID" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "prepayment-available",
    title: "待生成预付款实例",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/prepayment-available",
    description: "从已下单采购实例中勾选生成预付款合同草稿。",
    filters: [{ key: "keyword", label: "待生成实例", placeholder: "请输入批次、需求单、PO或实例编码" }],
    listFields: [
      { key: "id", label: "采购明细ID" },
      { key: "countryCode", label: "国家" },
      { key: "poNo", label: "PO单号" },
      { key: "requestItemId", label: "需求明细ID" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
    formFields: [
      { key: "id", label: "采购明细ID", required: true },
      { key: "countryCode", label: "国家" },
      { key: "poNo", label: "PO单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
  },
  {
    key: "prepayment-contracts",
    title: "预付款合同",
    table: "prepaymentcontracts",
    primaryKey: "contractNo",
    navGroup: "财务管理",
    route: "/finance/prepayment-contracts",
    description: "管理预付款合同草稿、确认状态和合同总金额。",
    filters: [
      { key: "keyword", label: "预付款合同", placeholder: "请输入合同号、状态或币种" },
      { key: "status", label: "状态", placeholder: "请选择状态" },
    ],
    listFields: [
      { key: "contractNo", label: "预付款合同号" },
      { key: "status", label: "状态" },
      { key: "currency", label: "币种" },
      { key: "effectiveDate", label: "生效日期", type: "date" },
      { key: "totalAmount", label: "合同总金额", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "contractNo", label: "预付款合同号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "currency", label: "币种" },
      { key: "effectiveDate", label: "生效日期", type: "date" },
      { key: "totalAmount", label: "合同总金额", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "monthly-prepayment-writeoffs",
    title: "预付款每月核销明细",
    table: "monthlyprepaymentwriteoffs",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/monthly-prepayment-writeoffs",
    description: "按月份查看已确认预付款合同生成的核销金额。",
    filters: [
      { key: "keyword", label: "月度核销", placeholder: "请输入合同号、批次、需求单、PO或实例编码" },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "currency", label: "币种" },
      { key: "originalAmount", label: "合同总价", type: "number" },
      { key: "monthlyAmount", label: "月核销金额", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    formFields: [
      { key: "id", label: "月度核销ID", required: true },
      { key: "contractNo", label: "预付款合同号", required: true },
      { key: "contractLineId", label: "合同明细ID", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "monthIndex", label: "月份序号", type: "number", required: true },
      { key: "totalMonths", label: "总月份", type: "number", required: true },
      { key: "currency", label: "币种" },
      { key: "originalAmount", label: "合同总价", type: "number" },
      { key: "monthlyAmount", label: "月核销金额", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "prepayment-writeoff-adjustments",
    title: "预付款核销调整单",
    table: "prepaymentwriteoffadjustments",
    primaryKey: "adjustmentNo",
    navGroup: "财务管理",
    route: "/finance/prepayment-writeoff-adjustments",
    description: "针对特定批次、实例、月份调整预付款每月核销金额。",
    filters: [
      { key: "keyword", label: "调整单", placeholder: "请输入调整单号、合同号、批次或实例编码" },
    ],
    listFields: [
      { key: "adjustmentNo", label: "调整单号" },
      { key: "status", label: "状态" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "differenceTotal", label: "调整差额合计", type: "number" },
      { key: "reason", label: "调整原因" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "adjustmentNo", label: "调整单号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "reason", label: "调整原因", type: "textarea" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "prepayment-contract-items",
    title: "预付款合同明细",
    table: "prepaymentcontractitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/finance/prepayment-contract-items",
    description: "管理预付款合同下的支付明细。",
    filters: [{ key: "keyword", label: "预付款", placeholder: "请输入合同号、币种或明细ID" }],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "contractNo", label: "合同号" },
      { key: "prepaymentAmount", label: "预付款金额", type: "number" },
      { key: "currency", label: "币种" },
      { key: "usdRate", label: "美元汇率", type: "number" },
      { key: "paymentDate", label: "支付日期", type: "date" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "contractNo", label: "合同号", required: true },
      { key: "prepaymentAmount", label: "预付款金额", type: "number" },
      { key: "currency", label: "币种" },
      { key: "usdRate", label: "美元汇率", type: "number" },
      { key: "paymentDate", label: "支付日期", type: "date" },
    ],
  },
  {
    key: "write-off-items",
    title: "核销明细",
    table: "writeoffitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/finance/write-off-items",
    description: "管理预付款与需求明细之间的核销关系。",
    filters: [{ key: "keyword", label: "核销", placeholder: "请输入核销ID或需求明细ID" }],
    listFields: [
      { key: "id", label: "核销ID" },
      { key: "requestItemId", label: "需求明细" },
      { key: "prepaymentContractItemId", label: "预付款明细" },
      { key: "prepaymentAmountUSD", label: "预付款USD", type: "number" },
      { key: "writeOffCurrency", label: "核销币种" },
      { key: "writeOffRate", label: "核销汇率", type: "number" },
      { key: "startMonth", label: "起始月份", type: "date" },
      { key: "totalMonths", label: "核销月数", type: "number" },
    ],
    formFields: [
      { key: "id", label: "核销ID", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "prepaymentContractItemId", label: "预付款明细ID", required: true },
      { key: "prepaymentAmountUSD", label: "预付款USD", type: "number" },
      { key: "writeOffCurrency", label: "核销币种" },
      { key: "writeOffRate", label: "核销汇率", type: "number" },
      { key: "startMonth", label: "起始月份", type: "date" },
      { key: "totalMonths", label: "核销月数", type: "number" },
    ],
  },
];

function getEntitiesByKeys(keys: string[]) {
  const keySet = new Set(keys);
  return entityConfigs.filter((entity) => keySet.has(entity.key));
}

const financeChildren: NonNullable<NavGroup["children"]> = [
  {
    title: "月账单管理",
    items: getEntitiesByKeys(["billing-available", "billing-ledgers", "monthly-billing-writeoffs"]),
  },
  {
    title: "预付款管理",
    items: getEntitiesByKeys([
      "prepayment-available",
      "prepayment-contracts",
      "monthly-prepayment-writeoffs",
      "prepayment-writeoff-adjustments",
    ]),
  },
  {
    title: "服务费核算",
    items: getEntitiesByKeys(["service-fees", "service-fee-snapshots", "service-fee-snapshot-items"]),
  },
];

export const navGroups: NavGroup[] = [
  {
    title: "财务管理",
    items: financeChildren.flatMap((child) => child.items),
    children: financeChildren,
  },
  {
    title: "合同管理",
    items: entityConfigs.filter((entity) => entity.navGroup === "合同管理"),
  },
  {
    title: "基础信息",
    items: entityConfigs.filter((entity) => entity.navGroup === "基础信息"),
  },
  {
    title: "客户需求",
    items: entityConfigs.filter((entity) => entity.navGroup === "客户需求"),
  },
  {
    title: "采购管理",
    items: entityConfigs.filter((entity) => entity.navGroup === "采购管理"),
  },
  {
    title: "物流管理",
    items: entityConfigs.filter((entity) => entity.navGroup === "物流管理"),
  },
];

export function getEntityConfig(key: string): EntityConfig | undefined {
  return entityConfigs.find((entity) => entity.key === key);
}
