import type { TableColumn } from "./table-utils";
import { PURCHASE_CURRENCY_OPTIONS } from "./purchase-order-form";
import { REQUEST_TYPE_OPTIONS } from "./request-type";
import { purchaseOrderPlanFieldSpecs, purchaseOrderSnFieldSpecs } from "./purchase-order-demand-plan-fields";

export type FieldType = "text" | "number" | "money" | "percentage" | "date" | "datetime" | "boolean" | "switch" | "textarea" | "select" | "lineType";

export type EntityField = TableColumn & {
  type?: FieldType;
  placeholder?: string;
  required?: boolean;
  readonly?: boolean;
  hidden?: boolean;
  allowCustom?: boolean;
  lookupSource?: "countries" | "datacenters" | "delivery-locations" | "delivery-contacts" | "b6-type-configs" | "product-categories";
  options?: Array<{ label: string; value: string }>;
};

export type EntityConfig = {
  key: string;
  title: string;
  table: string;
  primaryKey: string;
  uniqueKeys?: string[];
  navGroup: string;
  route: string;
  detailRoute?: string;
  description: string;
  adminOnly?: boolean;
  includeInFeatureToggles?: boolean;
  listFields: EntityField[];
  formFields: EntityField[];
  filters: EntityField[];
  defaultSort?: string;
  showSequence?: boolean;
};

export type NavGroup = {
  title: string;
  items: EntityConfig[];
  children?: NavChildGroup[];
};

export type NavChildGroup = {
  title: string;
  items: EntityConfig[];
  children?: NavChildGroup[];
};

export const entityConfigs: EntityConfig[] = [
  {
    key: "countries",
    title: "国家管理",
    table: "countries",
    primaryKey: "code",
    navGroup: "基础信息",
    route: "/master-data/countries",
    description: "维护国家代码及中英文名称。",
    filters: [{ key: "keyword", label: "国家", placeholder: "请输入国家代码或名称" }],
    listFields: [
      { key: "code", label: "国家代码" },
      { key: "nameZh", label: "国家中文名" },
      { key: "nameEn", label: "国家英文名" },
      { key: "nameLocal", label: "当地语言名称" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
    ],
    formFields: [
      { key: "code", label: "国家代码", required: true },
      { key: "nameZh", label: "国家中文名", required: true },
      { key: "nameEn", label: "国家英文名" },
      { key: "nameLocal", label: "当地语言名称" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
    ],
  },
  {
    key: "delivery-locations",
    title: "交付地址",
    table: "deliverylocations",
    primaryKey: "locationId",
    navGroup: "基础信息",
    route: "/master-data/delivery-locations",
    description: "维护仓库、办公室、机房、Broker 等交付站点。",
    filters: [
      { key: "keyword", label: "地点", placeholder: "请输入地点ID或名称" },
      { key: "countryCode", label: "国家", placeholder: "请选择国家" },
    ],
    listFields: [
      { key: "locationId", label: "地点ID" },
      { key: "countryCode", label: "国家" },
      { key: "locationType", label: "地点类型" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
      { key: "fullAddress", label: "详细地址" },
    ],
    formFields: [
      { key: "locationId", label: "地点ID", required: true },
      { key: "countryCode", label: "国家代码", required: true },
      { key: "locationType", label: "地点类型", required: true },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
      { key: "fullAddress", label: "详细地址", type: "textarea" },
    ],
  },
  {
    key: "delivery-contacts",
    title: "收件人信息",
    table: "deliverycontacts",
    primaryKey: "contactId",
    navGroup: "基础信息",
    route: "/master-data/delivery-contacts",
    description: "维护交付地址对应的联系人、电话和邮箱。",
    filters: [{ key: "keyword", label: "联系人", placeholder: "请输入姓名、电话或邮箱" }],
    listFields: [
      { key: "contactId", label: "联系人ID" },
      { key: "locationId", label: "所属地点" },
      { key: "name", label: "姓名" },
      { key: "phone", label: "电话" },
      { key: "email", label: "邮箱" },
    ],
    formFields: [
      { key: "contactId", label: "联系人ID", required: true },
      { key: "locationId", label: "所属地点ID", required: true },
      { key: "name", label: "姓名", required: true },
      { key: "phone", label: "电话" },
      { key: "email", label: "邮箱" },
    ],
  },
  {
    key: "datacenters",
    title: "机房管理",
    table: "datacenters",
    primaryKey: "dcCode",
    navGroup: "基础信息",
    route: "/master-data/datacenters",
    description: "维护机房与物理交付地址的绑定关系。",
    filters: [{ key: "keyword", label: "机房", placeholder: "请输入机房ID或名称" }],
    listFields: [
      { key: "dcCode", label: "机房ID" },
      { key: "locationId", label: "物理地址" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
    ],
    formFields: [
      { key: "dcCode", label: "机房ID", required: true },
      { key: "locationId", label: "物理地址", required: true, type: "textarea" },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
    ],
  },
  {
    key: "suppliers",
    title: "供应商管理",
    table: "common_suppliers",
    primaryKey: "supplierId",
    navGroup: "业务伙伴",
    route: "/suppliers",
    detailRoute: "/suppliers",
    defaultSort: "supplierCode ASC",
    description: "维护供应商完整基础资料。",
    filters: [
      { key: "keyword", label: "供应商", placeholder: "请输入供应商代码、中文名或简称" },
      { key: "supplierType", label: "供应商类型", type: "select", options: [{ label: "原厂", value: "manufacturer" }, { label: "代理商", value: "agent" }, { label: "集成商", value: "integrator" }, { label: "第三方", value: "third_party" }] },
      { key: "cooperationStatus", label: "合作状态", type: "select", options: [{ label: "正常合作", value: "normal" }, { label: "暂停合作", value: "suspended" }, { label: "终止合作", value: "terminated" }, { label: "未合作过", value: "not_cooperated" }] },
      { key: "status", label: "档案状态", type: "select", options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
    ],
    listFields: [
      { key: "supplierCode", label: "供应商编号" },
      { key: "nameCn", label: "供应商名称" },
      { key: "supplierType", label: "类型", type: "select", options: [{ label: "原厂", value: "manufacturer" }, { label: "代理商", value: "agent" }, { label: "集成商", value: "integrator" }, { label: "第三方", value: "third_party" }] },
      { key: "country", label: "国家/地区" },
      { key: "supplyCategories", label: "主要供应品类" },
      { key: "brands", label: "合作品牌" },
      { key: "cooperationStatus", label: "合作状态", type: "select", options: [{ label: "正常合作", value: "normal" }, { label: "暂停合作", value: "suspended" }, { label: "终止合作", value: "terminated" }, { label: "未合作过", value: "not_cooperated" }] },
      { key: "contactName", label: "默认联系人" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "supplierId", label: "供应商ID", hidden: true },
      { key: "supplierCode", label: "供应商编码", required: true },
      { key: "nameCn", label: "供应商全称（中文）", required: true },
      { key: "nameEn", label: "供应商全称（英文）" },
      { key: "shortName", label: "供应商简称" },
      { key: "country", label: "所在国家/地区" },
      { key: "city", label: "城市" },
      { key: "supplierType", label: "供应商类型", type: "select", options: [{ label: "原厂", value: "manufacturer" }, { label: "代理商", value: "agent" }, { label: "集成商", value: "integrator" }, { label: "第三方", value: "third_party" }] },
      { key: "registeredAddress", label: "注册地址", type: "textarea" },
      { key: "taxNumber", label: "税号" },
      { key: "supplyCategories", label: "主要供应品类" },
      { key: "brands", label: "合作品牌" },
      { key: "cooperationStatus", label: "合作状态", type: "select", options: [{ label: "正常合作", value: "normal" }, { label: "暂停合作", value: "suspended" }, { label: "终止合作", value: "terminated" }, { label: "未合作过", value: "not_cooperated" }] },
      { key: "status", label: "档案状态", type: "select", required: true, options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
      { key: "website", label: "官网" },
      { key: "remark", label: "备注", type: "textarea" },
      { key: "contactName", label: "默认联系人" },
      { key: "contactPhone", label: "联系电话" },
      { key: "contactEmail", label: "联系邮箱" },
    ],
  },
  {
    key: "instance-models",
    title: "实例型号",
    table: "instancemodels",
    primaryKey: "deviceCode",
    navGroup: "基础信息",
    route: "/master-data/instance-models",
    description: "维护设备编码、机型和实例型号名称。",
    filters: [
      { key: "keyword", label: "实例型号", placeholder: "请输入设备编码、机型或名称" },
    ],
    listFields: [
      { key: "deviceCode", label: "设备编码" },
      { key: "modelCode", label: "机型" },
      { key: "xxllCode", label: "xxll编码" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
      { key: "b6Type", label: "默认B6类型" },
    ],
    formFields: [
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "modelCode", label: "机型", required: true },
      { key: "xxllCode", label: "xxll编码" },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
      { key: "b6Type", label: "默认B6类型", placeholder: "选择或搜索B6类型", lookupSource: "b6-type-configs" },
    ],
  },
  {
    key: "undertaking-units",
    title: "承接单位管理",
    table: "common_undertaking_units",
    primaryKey: "undertakingUnitId",
    uniqueKeys: ["entityCode"],
    navGroup: "业务伙伴",
    route: "/undertaking-units",
    detailRoute: "/undertaking-units",
    defaultSort: "entityCode ASC",
    description: "维护承接单位完整基础资料。",
    filters: [{ key: "keyword", label: "承接单位", placeholder: "请输入承接单位代码、名称或简称" }, { key: "status", label: "状态", type: "select", options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] }],
    listFields: [
      { key: "entityCode", label: "承接单位编号" },
      { key: "entityName", label: "承接单位全称（中文）" },
      { key: "shortName", label: "简称" },
      { key: "country", label: "国家/地区" },
      { key: "status", label: "状态", type: "select", options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
      { key: "contactName", label: "联系人" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "undertakingUnitId", label: "承接单位ID", hidden: true },
      { key: "entityCode", label: "承接单位代码", required: true },
      { key: "entityName", label: "承接单位全称（中文）", required: true },
      { key: "undertakingUnitCode", label: "算力系统承接单位代码", hidden: true },
      { key: "name", label: "算力系统承接单位名称", hidden: true },
      { key: "nameEn", label: "承接单位全称（英文）" },
      { key: "shortName", label: "简称" },
      { key: "country", label: "所在国家/地区" },
      { key: "city", label: "城市" },
      { key: "registeredAddress", label: "注册地址", type: "textarea" },
      { key: "taxNumber", label: "税号" },
      { key: "cooperationStatus", label: "合作状态", type: "select", options: [{ label: "正常合作", value: "normal" }, { label: "暂停合作", value: "suspended" }, { label: "终止合作", value: "terminated" }, { label: "未合作过", value: "not_cooperated" }] },
      { key: "status", label: "档案状态", type: "select", required: true, options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
      { key: "website", label: "官网" },
      { key: "remark", label: "备注", type: "textarea" },
    ],
  },
  {
    key: "customers",
    title: "客户管理",
    table: "common_customers",
    primaryKey: "customerId",
    uniqueKeys: ["customerCode"],
    navGroup: "业务伙伴",
    route: "/customers",
    detailRoute: "/customers",
    defaultSort: "customerCode ASC",
    description: "维护客户完整基础资料。",
    filters: [{ key: "keyword", label: "客户", placeholder: "请输入客户代码、中文名或简称" }, { key: "status", label: "状态", type: "select", options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] }],
    listFields: [
      { key: "customerCode", label: "客户编号" },
      { key: "name", label: "客户全称（中文）" },
      { key: "shortName", label: "简称" },
      { key: "country", label: "国家/地区" },
      { key: "businessTypes", label: "合作业务" },
      { key: "cooperationStatus", label: "合作状态", type: "select", options: [{ label: "正常合作", value: "normal" }, { label: "暂停合作", value: "suspended" }, { label: "终止合作", value: "terminated" }, { label: "未合作过", value: "not_cooperated" }] },
      { key: "status", label: "状态", type: "select", options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
      { key: "contactName", label: "联系人" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "customerId", label: "客户ID", hidden: true },
      { key: "customerCode", label: "客户编码", required: true },
      { key: "name", label: "客户全称（中文）", required: true },
      { key: "nameEn", label: "客户全称（英文）" },
      { key: "shortName", label: "简称" },
      { key: "country", label: "所在国家/地区" },
      { key: "city", label: "城市" },
      { key: "address", label: "注册地址", type: "textarea" },
      { key: "taxNumber", label: "税号" },
      { key: "cooperationStatus", label: "合作状态", type: "select", options: [{ label: "正常合作", value: "normal" }, { label: "暂停合作", value: "suspended" }, { label: "终止合作", value: "terminated" }, { label: "未合作过", value: "not_cooperated" }] },
      { key: "businessTypes", label: "合作业务" },
      { key: "status", label: "档案状态", type: "select", required: true, options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
      { key: "website", label: "官网" },
      { key: "remark", label: "备注", type: "textarea" },
      { key: "contactName", label: "联系人" },
      { key: "contactPhone", label: "联系电话" },
      { key: "contactEmail", label: "联系邮箱" },
    ],
  },
  {
    key: "instance-contracts",
    title: "实例合同",
    table: "instancecontracts",
    primaryKey: "id",
    uniqueKeys: ["contractNo", "countryCode", "deviceCode"],
    navGroup: "合同管理",
    route: "/contracts/instance-contracts",
    description: "维护实例合同、国家、实例型号与分阶段含税单价。",
    filters: [
      { key: "keyword", label: "实例合同", placeholder: "请输入合同号、国家、设备编码或机型" },
    ],
    listFields: [
      { key: "id", label: "内部ID", defaultVisible: false },
      { key: "contractNo", label: "合同号" },
      { key: "countryCode", label: "国家" },
      { key: "deviceCode", label: "设备编码" },
      { key: "modelCode", label: "机型" },
      { key: "instanceModelEn", label: "实例型号（英文）" },
      { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "first24MonthPriceUSD", label: "前24个月含税单价", type: "money" },
      { key: "next36MonthPriceUSD", label: "后36个月含税单价", type: "money" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "contractNo", label: "合同号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "modelCode", label: "机型", readonly: true },
      { key: "instanceModelEn", label: "实例型号（英文）", readonly: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "first24MonthPriceUSD", label: "前24个月含税单价", type: "money", required: true },
      { key: "next36MonthPriceUSD", label: "后36个月含税单价", type: "money", required: true },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "requests",
    title: "需求单",
    table: "requests",
    primaryKey: "requestNo",
    navGroup: "客户需求",
    route: "/requests/orders",
    description: "以主从表单维护客户需求单和需求明细。",
    filters: [
      { key: "keyword", label: "需求单", placeholder: "请输入需求单号、合同号或批次" },
      { key: "status", label: "状态", placeholder: "请选择状态" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "requestNo", label: "需求单号" },
      { key: "countryCode", label: "国家" },
      { key: "contractNo", label: "合同号" },
      { key: "batchName", label: "批次名称" },
      { key: "requestType", label: "类型" },
      { key: "status", label: "状态" },
      { key: "createdByName", label: "创建人" },
      { key: "updatedByName", label: "修改人" },
      { key: "confirmedByName", label: "确认人" },
      { key: "plannedDeliveryDate", label: "计划交付日期", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "requestNo", label: "需求单号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "contractNo", label: "合同号", required: true },
      { key: "batchName", label: "批次名称", required: true },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS, required: true },
      { key: "status", label: "状态", required: true },
      { key: "plannedDeliveryDate", label: "计划交付日期", type: "date" },
      { key: "createdByUserId", label: "创建人ID", hidden: true },
      { key: "createdByName", label: "创建人", hidden: true },
      { key: "updatedByUserId", label: "修改人ID", hidden: true },
      { key: "updatedByName", label: "修改人", hidden: true },
      { key: "confirmedByUserId", label: "确认人ID", hidden: true },
      { key: "confirmedByName", label: "确认人", hidden: true },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "request-items",
    title: "需求明细一览",
    table: "requestitems",
    primaryKey: "id",
    navGroup: "客户需求",
    route: "/requests/items",
    description: "跨批次集中查看所有需求明细。",
    filters: [
      { key: "keyword", label: "需求明细", placeholder: "请输入需求单号、设备编码或供应商" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "requestNo", label: "需求单号" },
      { key: "requestType", label: "类型" },
      { key: "deviceCode", label: "设备编码" },
      { key: "supplierName", label: "供应商" },
      { key: "undertakingUnitName", label: "承接单位" },
      { key: "customerName", label: "客户" },
      { key: "requestedAt", label: "需求时间", type: "date" },
      { key: "quantity", label: "节点数量", type: "number" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "requestNo", label: "需求单号", required: true },
      { key: "requestType", label: "类型", readonly: true },
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "supplierId", label: "供应商ID", required: true },
      { key: "undertakingUnitId", label: "承接单位ID", required: true },
      { key: "customerId", label: "客户ID" },
      { key: "requestedAt", label: "需求时间", type: "date" },
      { key: "quantity", label: "节点数量", type: "number", required: true },
    ],
  },
  {
    key: "purchase-orders",
    title: "采购订单",
    table: "purchaseorders",
    primaryKey: "purchaseOrderId",
    navGroup: "采购管理",
    route: "/purchase/orders",
    description: "以主从表单维护 PO 主单和采购明细。",
    filters: [
      { key: "keyword", label: "采购订单", placeholder: "请输入PO订单号或币种" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "poNo", label: "PO订单号" },
      { key: "requestNo", label: "来源需求单号" },
      { key: "status", label: "采购状态" },
      { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "releasedAt", label: "下发日期", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "createdByName", label: "创建人" },
      { key: "updatedByName", label: "修改人" },
      { key: "confirmedByName", label: "确认人" },
    ],
    formFields: [
      { key: "poNo", label: "PO订单号", required: true },
      { key: "requestNo", label: "来源需求单号" },
      { key: "status", label: "采购状态", required: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "releasedAt", label: "下发日期", type: "date" },
      { key: "createdByUserId", label: "创建人ID", hidden: true },
      { key: "createdByName", label: "创建人", hidden: true },
      { key: "updatedByUserId", label: "修改人ID", hidden: true },
      { key: "updatedByName", label: "修改人", hidden: true },
      { key: "confirmedByUserId", label: "确认人ID", hidden: true },
      { key: "confirmedByName", label: "确认人", hidden: true },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "purchase-order-items",
    title: "采购明细一览",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "采购管理",
    route: "/purchase/items",
    description: "集中查看所有 PO 采购明细。",
    filters: [
      { key: "keyword", label: "采购明细", placeholder: "请输入PO订单号或需求明细ID" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "poNo", label: "PO订单号" },
      { key: "requestItemId", label: "需求明细" },
      { key: "requestType", label: "类型" },
      { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
      { key: "taxSurcharge", label: "税费加成", type: "money" },
      { key: "unitPrice", label: "含税单价", type: "money" },
      { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
      { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
      { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
      { key: "softwareCoefficient", label: "软件系数", type: "number" },
      { key: "totalCoefficient", label: "总系数", type: "number" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "poNo", label: "PO订单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
      { key: "taxSurcharge", label: "税费加成", type: "money" },
      { key: "unitPrice", label: "含税单价", type: "money" },
      { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
      { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
      { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
      { key: "softwareCoefficient", label: "软件系数", type: "number" },
      { key: "totalCoefficient", label: "总系数", type: "number" },
    ],
  },
  {
    key: "shipments",
    title: "物流列表",
    table: "shipments",
    primaryKey: "shipmentId",
    navGroup: "物流管理",
    route: "/shipments",
    description: "管理 PO 发运、交付快照和物流时间线。",
    defaultSort: "createdAt DESC",
    filters: [
      { key: "keyword", label: "物流", placeholder: "请输入物流ID、PO订单号或收件人" },
      { key: "countryCode", label: "国家", type: "select", lookupSource: "countries" },
      { key: "transportMode", label: "运输方式", placeholder: "请选择运输方式" },
      {
        key: "receiptStatus",
        label: "签收状态",
        type: "select",
        options: [
          { label: "已签收", value: "received" },
          { label: "未签收", value: "unreceived" },
        ],
      },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "shipmentId", label: "物流ID" },
      { key: "poNo", label: "PO订单号" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "purchaseOrderItemId", label: "采购明细ID" },
      { key: "deviceCode", label: "实例编码" },
      { key: "nameEn", label: "实例名称（英文）" },
      { key: "undertakingUnitName", label: "承接单位" },
      { key: "supplierName", label: "供应商" },
      { key: "customerName", label: "客户" },
      { key: "dcNameZh", label: "机房" },
      { key: "destinationAddress", label: "收货地址" },
      { key: "recipientName", label: "收件人" },
      { key: "snapshotDestinationAddress", label: "交付地址快照", defaultVisible: false },
      { key: "snapshotRecipientName", label: "收件人快照", defaultVisible: false },
      { key: "snapshotRecipientPhone", label: "收件电话快照", defaultVisible: false },
      { key: "transportMode", label: "运输方式" },
      { key: "isReceived", label: "是否签收", type: "boolean" },
      { key: "crd", label: "CRD", type: "date" },
      { key: "apdAt", label: "APD交单", type: "date" },
      { key: "pickupAt", label: "ASD提货", type: "date" },
      { key: "departedAt", label: "起飞/开船", type: "date" },
      { key: "arrivedAt", label: "到港", type: "date" },
      { key: "customsClearedAt", label: "清关完成", type: "date" },
      { key: "deliveredAt", label: "派送", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime", defaultVisible: false },
      { key: "updatedAt", label: "更新时间", type: "datetime", defaultVisible: false },
    ],
    formFields: [
      { key: "shipmentId", label: "物流ID", required: true },
      { key: "poNo", label: "PO订单号", required: true },
      { key: "batchName", label: "批次号" },
      { key: "purchaseOrderItemId", label: "采购明细ID" },
      { key: "deviceCode", label: "实例编码" },
      { key: "nameEn", label: "实例名称（英文）" },
      { key: "dcCode", label: "机房ID", lookupSource: "datacenters", placeholder: "输入机房ID或中文名称搜索" },
      { key: "dcNameZh", label: "机房中文名称" },
      { key: "destinationLocationId", label: "目的地点ID", lookupSource: "delivery-locations", placeholder: "输入地点ID、名称或地址搜索" },
      { key: "recipientContactId", label: "收件联系人ID", lookupSource: "delivery-contacts", placeholder: "输入联系人ID、姓名或电话搜索" },
      { key: "snapshotDestinationAddress", label: "交付地址快照", type: "textarea" },
      { key: "snapshotRecipientName", label: "收件人快照" },
      { key: "snapshotRecipientPhone", label: "收件电话快照" },
      { key: "transportMode", label: "运输方式" },
      { key: "crd", label: "CRD", type: "date" },
      { key: "apdAt", label: "APD交单", type: "date" },
      { key: "pickupAt", label: "ASD提货", type: "date" },
      { key: "departedAt", label: "起飞/开船", type: "date" },
      { key: "arrivedAt", label: "到港", type: "date" },
      { key: "customsClearedAt", label: "清关完成", type: "date" },
      { key: "deliveredAt", label: "派送", type: "date" },
    ],
  },
  {
    key: "billing-available",
    title: "待生成月账单实例",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/billing-available",
    description: "从已确认下单且尚未生成月账单台账的实例中生成60个月账单。",
    filters: [
      { key: "keyword", label: "待生成月账单", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "采购明细ID" },
      { key: "poNo", label: "PO单号" },
      { key: "requestItemId", label: "需求明细ID" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
    formFields: [
      { key: "id", label: "采购明细ID", required: true },
      { key: "poNo", label: "PO单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
  },
  {
    key: "billing-ledgers",
    title: "月账单台账",
    table: "billinginstanceledgers",
    primaryKey: "ledgerId",
    navGroup: "财务管理",
    route: "/finance/billing-ledgers",
    description: "查看已确认月账单实例的合同价格锁定信息。",
    filters: [
      { key: "keyword", label: "月账单台账", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "ledgerId", label: "台账ID" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "contractCurrency", label: "合同币种" },
      { key: "first24MonthPrice", label: "前24个月合同价", type: "money" },
      { key: "next36MonthPrice", label: "后36个月合同价", type: "money" },
      { key: "startMonth", label: "起始核销月份", type: "date" },
      { key: "status", label: "状态" },
    ],
    formFields: [
      { key: "ledgerId", label: "台账ID", required: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "actualCurrency", label: "实际币种" },
      { key: "actualUnitPrice", label: "实际单价", type: "money" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "contractCurrency", label: "合同币种" },
      { key: "first24MonthPrice", label: "前24个月合同价", type: "money" },
      { key: "next36MonthPrice", label: "后36个月合同价", type: "money" },
      { key: "startMonth", label: "起始核销月份", type: "date" },
      { key: "status", label: "状态" },
    ],
    defaultSort: "confirmedAt DESC",
  },
  {
    key: "monthly-billing-writeoffs",
    title: "月账单每月明细",
    table: "monthlybillingwriteoffs",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/monthly-billing-writeoffs",
    description: "查看月账单台账生成的60个月实例核销明细。",
    filters: [
      { key: "keyword", label: "月账单明细", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "currency", label: "币种" },
      { key: "monthlyAmount", label: "月账单实例价格（含税）", type: "money" },
      { key: "monthlyTotalAmount", label: "月账单金额（含税）", type: "money" },
      { key: "selfCalculatedUnitPrice", label: "24个月实例单价（含税自算）", type: "number" },
      { key: "differenceUnitPrice", label: "结差差额单价", type: "money" },
      { key: "differenceTotalPrice", label: "结差差额总价", type: "money" },
      { key: "stage", label: "阶段" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "ledgerId", label: "台账ID", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "monthIndex", label: "月份序号", type: "number" },
      { key: "stage", label: "阶段" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "currency", label: "币种" },
      { key: "monthlyAmount", label: "月账单实例价格（含税）", type: "money" },
      { key: "monthlyTotalAmount", label: "月账单金额（含税）", type: "money" },
      { key: "selfCalculatedUnitPrice", label: "24个月实例单价（含税自算）", type: "number" },
      { key: "differenceUnitPrice", label: "结差差额单价", type: "money" },
      { key: "differenceTotalPrice", label: "结差差额总价", type: "money" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "billing-adjustments",
    title: "实例合同调整单",
    table: "billingadjustments",
    primaryKey: "adjustmentNo",
    navGroup: "合同管理",
    route: "/finance/billing-adjustments",
    description: "维护特定批次、特定实例在某个生效月份之后的月账单价格调整。",
    filters: [{ key: "keyword", label: "调整单", placeholder: "请输入调整单号、合同号、国家、批次或实例编码" }],
    listFields: [
      { key: "adjustmentNo", label: "调整单号" },
      { key: "instanceContractNo", label: "实例合同单号" },
      { key: "status", label: "状态" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "reason", label: "调整原因" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    formFields: [
      { key: "adjustmentNo", label: "调整单号", required: true },
      { key: "instanceContractNo", label: "实例合同单号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "reason", label: "调整原因", type: "textarea" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "billing-statements",
    title: "月账单对账单",
    table: "billingstatementsnapshots",
    primaryKey: "snapshotNo",
    navGroup: "财务管理",
    route: "/finance/billing-statements",
    description: "按国家、期间和币种生成月账单对账单，确认后冻结并按模板导出 Excel。",
    filters: [
      { key: "keyword", label: "对账单", placeholder: "请输入快照编号、国家或币种" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
    ],
    listFields: [
      { key: "snapshotNo", label: "快照编号" },
      { key: "countryCode", label: "国家" },
      { key: "startDate", label: "起始日期", type: "date" },
      { key: "endDate", label: "终止日期", type: "date" },
      { key: "currencySummary", label: "币种汇总" },
      { key: "totalQuantity", label: "总数量", type: "number" },
      { key: "totalAmount", label: "总金额", type: "money" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
    ],
    formFields: [
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "startDate", label: "起始日期", type: "date", required: true },
      { key: "endDate", label: "终止日期", type: "date", required: true },
      { key: "currencySummary", label: "币种汇总" },
      { key: "totalQuantity", label: "总数量", type: "number" },
      { key: "totalAmount", label: "总金额", type: "money" },
      { key: "itemCount", label: "明细数量", type: "number" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "service-fees",
    title: "服务费核算",
    table: "servicefeesnapshotitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/service-fees",
    description: "按月度月账单核销总额减预付款核销金额，实时核算服务费并生成服务费对账单草稿。",
    filters: [
      { key: "keyword", label: "服务费核算", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitId", label: "承接单位" },
      { key: "supplierId", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "billingSourceIds", label: "月账单来源ID" },
      { key: "prepaymentSourceIds", label: "预付款来源ID" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
  },
  {
    key: "service-fee-snapshots",
    title: "服务费对账单",
    table: "servicefeesnapshots",
    primaryKey: "snapshotNo",
    navGroup: "财务管理",
    route: "/finance/service-fee-snapshots",
    description: "按国家和核销月份管理服务费对账单、确认状态、开票状态及发票附件。",
    filters: [
      { key: "keyword", label: "对账单", placeholder: "请输入对账单号、国家或附件名" },
      { key: "writeOffMonth", label: "核销月份", placeholder: "核销月份", type: "date" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
      { key: "status", label: "确认状态", type: "select", options: [{ label: "未确认", value: "未确认" }, { label: "已确认", value: "已确认" }] },
      { key: "invoiceStatus", label: "开票状态", type: "select", options: [{ label: "未开票", value: "未开票" }, { label: "已开票", value: "已开票" }] },
      { key: "repaymentStatus", label: "回款状态", type: "select", options: [{ label: "未回款", value: "未回款" }, { label: "已回款", value: "已回款" }] },
    ],
    listFields: [
      { key: "snapshotNo", label: "对账单号" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "undertakingUnitName", label: "承接单位" },
      { key: "customerName", label: "客户" },
      { key: "status", label: "状态" },
      { key: "billingTotal", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentTotal", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeTotal", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeTotalExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "instanceServiceFeeTotal", label: "实例服务费合计", type: "money" },
      { key: "feeServiceFeeTotal", label: "非实例费用合计", type: "money" },
      { key: "repaymentStatus", label: "是否回款", type: "switch" },
      { key: "receivingUnitCode", label: "收款单位" },
      { key: "payerCustomerCode", label: "付款单位" },
      { key: "repaymentCurrency", label: "回款币种" },
      { key: "repaymentAmount", label: "回款含税金额", type: "money" },
      { key: "repaymentAmountExcludingTax", label: "回款未税金额", type: "money" },
      { key: "repaymentVatRate", label: "回款税率（%）", type: "percentage" },
      { key: "repaymentDate", label: "回款日期", type: "date" },
      { key: "invoiceNo", label: "发票号" },
      { key: "invoiceCurrency", label: "发票币种" },
      { key: "invoiceAmountExcludingTax", label: "发票未税金额", type: "money" },
      { key: "invoiceVatRate", label: "发票税率（%）", type: "percentage" },
      { key: "invoiceAmountIncludingTax", label: "发票含税金额", type: "money" },
      { key: "invoiceStatus", label: "开票状态" },
      { key: "invoiceOriginalName", label: "发票附件" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    formFields: [
      { key: "snapshotNo", label: "对账单号", required: true },
      { key: "status", label: "状态" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "billingTotal", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentTotal", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeTotal", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeTotalExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "instanceServiceFeeTotal", label: "实例服务费合计", type: "money" },
      { key: "feeServiceFeeTotal", label: "非实例费用合计", type: "money" },
      { key: "repaymentStatus", label: "是否回款", type: "switch" },
      { key: "receivingUnitId", label: "收款单位" },
      { key: "payerCustomerId", label: "付款单位" },
      { key: "repaymentCurrency", label: "回款币种" },
      { key: "repaymentAmount", label: "回款含税金额", type: "money" },
      { key: "repaymentAmountExcludingTax", label: "回款未税金额", type: "money" },
      { key: "repaymentVatRate", label: "回款税率（%）", type: "percentage" },
      { key: "repaymentDate", label: "回款日期", type: "date" },
      { key: "invoiceNo", label: "发票号" },
      { key: "invoiceCurrency", label: "发票币种" },
      { key: "invoiceAmountExcludingTax", label: "发票未税金额", type: "money" },
      { key: "invoiceVatRate", label: "发票税率（%）", type: "percentage" },
      { key: "invoiceAmountIncludingTax", label: "发票含税金额", type: "money" },
      { key: "invoiceStatus", label: "开票状态" },
      { key: "invoiceOriginalName", label: "发票附件" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    defaultSort: "writeOffMonth DESC, createdAt DESC",
  },
  {
    key: "service-fee-snapshot-items",
    title: "服务费对账单明细",
    table: "servicefeesnapshotitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/service-fee-snapshot-items",
    description: "查看服务费对账单中冻结保存的明细行。",
    filters: [
      { key: "keyword", label: "对账单明细", placeholder: "请输入对账单号、批次、需求单、PO或实例编码" },
      { key: "snapshotNo", label: "对账单号", placeholder: "对账单号" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
      { key: "batchName", label: "批次", placeholder: "批次" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "snapshotNo", label: "对账单号" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "snapshotNo", label: "对账单号", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "countryCode", label: "国家" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "billingSourceIds", label: "月账单来源ID" },
      { key: "prepaymentSourceIds", label: "预付款来源ID" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "prepayment-available",
    title: "待生成预付款实例",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/prepayment-available",
    description: "从已下单采购实例中勾选生成预付款合同草稿。",
    filters: [
      { key: "keyword", label: "待生成实例", placeholder: "请输入批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "采购明细ID" },
      { key: "countryCode", label: "国家" },
      { key: "poNo", label: "PO单号" },
      { key: "requestItemId", label: "需求明细ID" },
      { key: "requestType", label: "类型" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
    formFields: [
      { key: "id", label: "采购明细ID", required: true },
      { key: "countryCode", label: "国家" },
      { key: "poNo", label: "PO单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "requestType", label: "类型" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
  },
  {
    key: "prepayment-contracts",
    title: "预付款合同",
    table: "prepaymentcontracts",
    primaryKey: "contractNo",
    navGroup: "财务管理",
    route: "/finance/prepayment-contracts",
    description: "管理预付款合同草稿、确认状态和合同总金额。",
    filters: [
      { key: "keyword", label: "预付款合同", placeholder: "请输入合同号、状态或币种" },
      { key: "status", label: "状态", placeholder: "请选择状态" },
    ],
    listFields: [
      { key: "contractNo", label: "预付款合同号" },
      { key: "status", label: "状态" },
      { key: "currency", label: "币种" },
      { key: "effectiveDate", label: "生效日期", type: "date" },
      { key: "totalAmount", label: "合同总金额", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "contractNo", label: "预付款合同号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "currency", label: "币种" },
      { key: "effectiveDate", label: "生效日期", type: "date" },
      { key: "totalAmount", label: "合同总金额", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "monthly-prepayment-writeoffs",
    title: "预付款每月核销明细",
    table: "monthlyprepaymentwriteoffs",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/monthly-prepayment-writeoffs",
    description: "按月份查看已确认预付款合同生成的核销金额。",
    filters: [
      { key: "keyword", label: "月度核销", placeholder: "请输入合同号、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "currency", label: "币种" },
      { key: "originalAmount", label: "合同总价", type: "number" },
      { key: "monthlyAmount", label: "月核销金额", type: "money" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    formFields: [
      { key: "id", label: "月度核销ID", required: true },
      { key: "contractNo", label: "预付款合同号", required: true },
      { key: "contractLineId", label: "合同明细ID", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "monthIndex", label: "月份序号", type: "number", required: true },
      { key: "totalMonths", label: "总月份", type: "number", required: true },
      { key: "currency", label: "币种" },
      { key: "originalAmount", label: "合同总价", type: "number" },
      { key: "monthlyAmount", label: "月核销金额", type: "money" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "prepayment-writeoff-adjustments",
    title: "预付款核销调整单",
    table: "prepaymentwriteoffadjustments",
    primaryKey: "adjustmentNo",
    navGroup: "财务管理",
    route: "/finance/prepayment-writeoff-adjustments",
    description: "针对特定批次、实例、月份调整预付款每月核销金额。",
    filters: [
      { key: "keyword", label: "调整单", placeholder: "请输入调整单号、合同号、批次或实例编码" },
    ],
    listFields: [
      { key: "adjustmentNo", label: "调整单号" },
      { key: "status", label: "状态" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "differenceTotal", label: "调整差额合计", type: "number" },
      { key: "reason", label: "调整原因" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "adjustmentNo", label: "调整单号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "reason", label: "调整原因", type: "textarea" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "prepayment-contract-items",
    title: "预付款合同明细",
    table: "prepaymentcontractitems",
    primaryKey: "id",
    navGroup: "基础信息",
    route: "/finance/prepayment-contract-items",
    description: "管理预付款合同下的支付明细。",
    filters: [
      { key: "keyword", label: "预付款", placeholder: "请输入合同号、币种或明细ID" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "contractNo", label: "合同号" },
      { key: "requestType", label: "类型" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "prepaymentAmount", label: "预付款金额", type: "money" },
      { key: "currency", label: "币种" },
      { key: "usdRate", label: "美元汇率", type: "number" },
      { key: "paymentDate", label: "支付日期", type: "date" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "contractNo", label: "合同号", required: true },
      { key: "requestType", label: "类型", readonly: true },
      { key: "prepaymentAmount", label: "预付款金额", type: "money" },
      { key: "currency", label: "币种" },
      { key: "usdRate", label: "美元汇率", type: "number" },
      { key: "paymentDate", label: "支付日期", type: "date" },
    ],
  },
  {
    key: "write-off-items",
    title: "核销明细",
    table: "writeoffitems",
    primaryKey: "id",
    navGroup: "基础信息",
    route: "/finance/write-off-items",
    description: "管理预付款与需求明细之间的核销关系。",
    filters: [{ key: "keyword", label: "核销", placeholder: "请输入核销ID或需求明细ID" }],
    listFields: [
      { key: "id", label: "核销ID" },
      { key: "requestItemId", label: "需求明细" },
      { key: "prepaymentContractItemId", label: "预付款明细" },
      { key: "prepaymentAmountUSD", label: "预付款USD", type: "money" },
      { key: "writeOffCurrency", label: "核销币种" },
      { key: "writeOffRate", label: "核销汇率", type: "number" },
      { key: "startMonth", label: "起始月份", type: "date" },
      { key: "totalMonths", label: "核销月数", type: "number" },
    ],
    formFields: [
      { key: "id", label: "核销ID", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "prepaymentContractItemId", label: "预付款明细ID", required: true },
      { key: "prepaymentAmountUSD", label: "预付款USD", type: "money" },
      { key: "writeOffCurrency", label: "核销币种" },
      { key: "writeOffRate", label: "核销汇率", type: "number" },
      { key: "startMonth", label: "起始月份", type: "date" },
      { key: "totalMonths", label: "核销月数", type: "number" },
    ],
  },
];

const purchaseOrderConfig = entityConfigs.find((entity) => entity.key === "purchase-orders");
if (purchaseOrderConfig) {
  purchaseOrderConfig.primaryKey = "purchaseOrderId";
  purchaseOrderConfig.listFields = [
    { key: "purchaseOrderId", label: "系统采购ID", defaultVisible: false },
    { key: "poNo", label: "PO订单号" },
    { key: "requestNo", label: "来源需求单号" },
    { key: "countryCode", label: "国家" },
    { key: "requestType", label: "类型" },
    { key: "status", label: "采购状态" },
    { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
    { key: "releasedAt", label: "下发日期", type: "date" },
    { key: "createdAt", label: "创建时间", type: "datetime" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
    { key: "createdByName", label: "创建人" },
    { key: "updatedByName", label: "修改人" },
    { key: "confirmedByName", label: "确认人" },
  ];
  purchaseOrderConfig.formFields = [
    { key: "purchaseOrderId", label: "系统采购ID", required: true },
    { key: "poNo", label: "PO订单号", required: true },
    { key: "requestNo", label: "来源需求单号" },
    { key: "status", label: "采购状态", required: true },
    { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
    { key: "releasedAt", label: "下发日期", type: "date" },
    { key: "createdByUserId", label: "创建人ID", hidden: true },
    { key: "createdByName", label: "创建人", hidden: true },
    { key: "updatedByUserId", label: "修改人ID", hidden: true },
    { key: "updatedByName", label: "修改人", hidden: true },
    { key: "confirmedByUserId", label: "确认人ID", hidden: true },
    { key: "confirmedByName", label: "确认人", hidden: true },
  ];
  purchaseOrderConfig.defaultSort = "updatedAt DESC";
}

const purchaseOrderItemConfig = entityConfigs.find((entity) => entity.key === "purchase-order-items");
if (purchaseOrderItemConfig) {
  purchaseOrderItemConfig.listFields = [
    { key: "id", label: "明细ID" },
    { key: "purchaseOrderId", label: "系统采购ID", defaultVisible: false },
    { key: "poNo", label: "PO订单号" },
    { key: "requestNo", label: "来源需求单号" },
    { key: "requestItemId", label: "需求明细" },
    { key: "requestType", label: "类型" },
    { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
    { key: "taxSurcharge", label: "税费加成", type: "money" },
    { key: "unitPrice", label: "含税单价", type: "money" },
    { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
    { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
    { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
    { key: "softwareCoefficient", label: "软件系数", type: "number" },
    { key: "totalCoefficient", label: "总系数", type: "number" },
  ];
  purchaseOrderItemConfig.formFields = [
    { key: "id", label: "明细ID", required: true },
    { key: "purchaseOrderId", label: "系统采购ID" },
    { key: "poNo", label: "PO订单号", required: true },
    { key: "requestNo", label: "来源需求单号" },
    { key: "requestItemId", label: "需求明细ID", required: true },
    { key: "requestType", label: "类型", readonly: true },
    { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
    { key: "taxSurcharge", label: "税费加成", type: "money" },
    { key: "unitPrice", label: "含税单价", type: "money" },
    { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
    { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
    { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
    { key: "softwareCoefficient", label: "软件系数", type: "number" },
    { key: "totalCoefficient", label: "总系数", type: "number" },
  ];
}

entityConfigs.push(
  {
    key: "purchase-order-sn-items",
    title: "要货计划SN码",
    table: "purchaseordersnitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/purchase/order-sn-items",
    description: "维护采购订单实例对应的SN码和资产层级信息。",
    showSequence: true,
    filters: [{ key: "keyword", label: "要货计划SN码", placeholder: "请输入PO订单号、SN或固定资产编码" }],
    listFields: [
      { key: "requestNo", label: "要货需求单号" },
      { key: "shippingBatch", label: "发货批次" },
      { key: "deviceVendor", label: "设备厂商" },
      { key: "finalParentSn", label: "最终父项SN" },
      { key: "finalParentPn", label: "甲方最终父项PN" },
      { key: "finalParentPnDescription", label: "最终父项PN描述" },
      { key: "supplierFinalParentCode", label: "供应商最终父项编码" },
      { key: "finalParentCode", label: "甲方最终父项编码" },
      { key: "level", label: "层级" },
      { key: "supplierParentCode", label: "供应商父项编码" },
      { key: "supplierParentSn", label: "供应商父项SN" },
      { key: "parentCode", label: "甲方父项编码" },
      { key: "componentCategory", label: "部件类别" },
      { key: "sn", label: "供应商子项部件SN" },
      { key: "fixedAssetCode", label: "固定资产编码" },
      { key: "poNo", label: "PO" },
      { key: "materialDescription", label: "物料描述" },
      { key: "parentAssetNo", label: "甲方父项固资号" },
      { key: "packingListNo", label: "箱单号" },
      { key: "supplierChildComponentCode", label: "供应商子项部件编码" },
      { key: "customerChildComponentCode", label: "甲方子项部件编码" },
      { key: "supplierChildComponentDescription", label: "供应商子项部件描述" },
      { key: "childComponentOriginalPn", label: "子项部件原厂PN" },
      { key: "childComponentOriginalSn", label: "子项部件原厂SN" },
      { key: "rackUnit", label: "U位" },
      { key: "site", label: "站点" },
      { key: "contactPhone", label: "联系人/电话" },
    ],
    formFields: [
      { key: "id", label: "明细ID", hidden: true },
      { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
      { key: "poNo", label: "PO订单号", hidden: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
      { key: "requestNo", label: "要货需求单号" },
      { key: "shippingBatch", label: "发货批次" },
      { key: "deviceVendor", label: "设备厂商" },
      { key: "finalParentSn", label: "最终父项SN" },
      { key: "finalParentPn", label: "甲方最终父项PN" },
      { key: "finalParentPnDescription", label: "最终父项PN描述" },
      { key: "supplierFinalParentCode", label: "供应商最终父项编码" },
      { key: "finalParentCode", label: "甲方最终父项编码" },
      { key: "level", label: "层级" },
      { key: "supplierParentCode", label: "供应商父项编码" },
      { key: "supplierParentSn", label: "供应商父项SN" },
      { key: "parentCode", label: "甲方父项编码" },
      { key: "componentCategory", label: "部件类别" },
      { key: "sn", label: "供应商子项部件SN", required: true },
      { key: "fixedAssetCode", label: "固定资产编码" },
      { key: "materialDescription", label: "物料描述" },
      { key: "parentAssetNo", label: "甲方父项固资号" },
      { key: "packingListNo", label: "箱单号" },
      { key: "supplierChildComponentCode", label: "供应商子项部件编码" },
      { key: "customerChildComponentCode", label: "甲方子项部件编码" },
      { key: "supplierChildComponentDescription", label: "供应商子项部件描述" },
      { key: "childComponentOriginalPn", label: "子项部件原厂PN" },
      { key: "childComponentOriginalSn", label: "子项部件原厂SN" },
      { key: "rackUnit", label: "U位" },
      { key: "site", label: "站点" },
      { key: "contactPhone", label: "联系人/电话" },
    ],
    defaultSort: "updatedAt DESC",
  },
  {
    key: "purchase-order-plan-items",
    title: "要货计划子",
    table: "purchaseorderplanitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/purchase/order-plan-items",
    description: "维护采购订单的要货计划和供应商交期反馈。",
    showSequence: true,
    filters: [{ key: "keyword", label: "要货计划子", placeholder: "请输入PO订单号、物料或要货计划子ID" }],
    listFields: [
      { key: "sourcePlanId", label: "ID" },
      { key: "quoteReceivedAt", label: "算力供应商收到CEG报价时间", type: "date" },
      { key: "poIssuedAt", label: "算力PO下发时间", type: "date" },
      { key: "receiptProofUploadedAt", label: "签收证明上传时间", type: "date" },
      { key: "logisticsReceivedAt", label: "物流签收时间", type: "date" },
      { key: "ataAt", label: "ATA时间", type: "date" },
      { key: "ata", label: "ATA" },
      { key: "supplierCpd", label: "供应商反馈CPD", type: "date" },
      { key: "material", label: "物料" },
    ],
    formFields: [
      { key: "id", label: "明细ID", hidden: true },
      { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
      { key: "poNo", label: "PO订单号", hidden: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
      { key: "requestNo", label: "需求单号", hidden: true },
      { key: "sourcePlanId", label: "要货计划子ID" },
      { key: "quoteReceivedAt", label: "算力供应商收到CEG报价时间", type: "date" },
      { key: "poIssuedAt", label: "算力PO下发时间", type: "date" },
      { key: "receiptProofUploadedAt", label: "签收证明上传时间", type: "date" },
      { key: "logisticsReceivedAt", label: "物流签收时间", type: "date" },
      { key: "ataAt", label: "ATA时间", type: "date" },
      { key: "ata", label: "ATA" },
      { key: "supplierCpd", label: "供应商反馈CPD", type: "date" },
      { key: "material", label: "物料" },
    ],
    defaultSort: "updatedAt DESC",
  },
);

const purchaseOrderSnConfig = entityConfigs.find((entity) => entity.key === "purchase-order-sn-items");
if (purchaseOrderSnConfig) {
  purchaseOrderSnConfig.listFields = purchaseOrderSnFieldSpecs;
  purchaseOrderSnConfig.formFields = [
    { key: "id", label: "明细ID", hidden: true },
    { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
    { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
    { key: "requestNo", label: "需求单号", hidden: true },
    ...purchaseOrderSnFieldSpecs.map((field) =>
      field.key === "poNo" ? { ...field, readonly: true } : field,
    ),
  ];
}

const purchaseOrderPlanConfig = entityConfigs.find((entity) => entity.key === "purchase-order-plan-items");
if (purchaseOrderPlanConfig) {
  purchaseOrderPlanConfig.listFields = purchaseOrderPlanFieldSpecs;
  purchaseOrderPlanConfig.formFields = [
    { key: "id", label: "明细ID", hidden: true },
    { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
    { key: "poNo", label: "PO订单号", hidden: true },
    { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
    { key: "requestNo", label: "需求单号", hidden: true },
    ...purchaseOrderPlanFieldSpecs,
  ];
}

function getEntitiesByKeys(keys: string[]) {
  const entityByKey = new Map(entityConfigs.map((entity) => [entity.key, entity]));
  return keys.map((key) => entityByKey.get(key)).filter((entity): entity is EntityConfig => Boolean(entity));
}

entityConfigs.push({
  key: "customer-pos",
  title: "客户PO",
  table: "po_customer_pos",
  primaryKey: "id",
  uniqueKeys: ["poNo"],
  navGroup: "客户PO",
  route: "/customer-pos",
  description: "登记客户采购订单，并按产品主档编码进行匹配。",
  filters: [
    { key: "keyword", label: "客户PO", placeholder: "请输入客户PO号或客户ID" },
    { key: "status", label: "状态", type: "select", options: [{ label: "草稿", value: "draft" }, { label: "已确认", value: "confirmed" }] },
  ],
  listFields: [
    { key: "poNo", label: "客户PO号", sortable: true, filterable: true },
    { key: "customerId", label: "客户", sortable: true, filterable: true },
    { key: "poDate", label: "PO日期", type: "date" },
    { key: "deliveryDate", label: "交付日期", type: "date" },
    { key: "currency", label: "币种" },
    { key: "status", label: "状态", sortable: true, filterable: true },
    { key: "quotationNo", label: "关联报价单" },
    { key: "createdByName", label: "创建人" },
    { key: "updatedByName", label: "修改人" },
    { key: "confirmedByName", label: "确认人" },
    { key: "createdAt", label: "创建时间", type: "datetime" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "poNo", label: "客户PO号", required: true },
    { key: "customerId", label: "客户ID", required: true },
    { key: "poDate", label: "PO日期", type: "date", required: true },
    { key: "deliveryDate", label: "交付日期", type: "date" },
    { key: "currency", label: "币种", required: true },
    { key: "status", label: "状态", type: "select", required: true, options: [{ label: "草稿", value: "draft" }, { label: "已确认", value: "confirmed" }] },
    { key: "remark", label: "备注", type: "textarea" },
    { key: "createdByUserId", label: "创建人ID", hidden: true },
    { key: "createdByName", label: "创建人", hidden: true },
    { key: "updatedByUserId", label: "修改人ID", hidden: true },
    { key: "updatedByName", label: "修改人", hidden: true },
    { key: "confirmedByUserId", label: "确认人ID", hidden: true },
    { key: "confirmedByName", label: "确认人", hidden: true },
  ],
  defaultSort: "updatedAt DESC",
}, {
  key: "customer-po-items",
  title: "客户PO明细",
  table: "po_customer_po_items",
  primaryKey: "id",
  navGroup: "隐藏",
  route: "/customer-pos/items",
  description: "维护客户PO明细及产品主档匹配结果。",
  filters: [{ key: "keyword", label: "客户PO明细", placeholder: "请输入客户产品名称或产品编码" }],
  listFields: [
    { key: "poId", label: "客户PO ID" },
    { key: "lineNo", label: "行号", type: "number" },
    { key: "customerProductName", label: "客户产品名称" },
    { key: "customerSpec", label: "客户规格" },
    { key: "quantity", label: "数量", type: "number" },
    { key: "matchedProductCode", label: "匹配产品编码" },
    { key: "matchStatus", label: "匹配状态" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "poId", label: "客户PO ID", required: true },
    { key: "lineNo", label: "行号", type: "number", required: true },
    { key: "customerSku", label: "客户SKU" },
    { key: "customerProductName", label: "客户产品名称", required: true },
    { key: "customerSpec", label: "客户规格" },
    { key: "customerBrand", label: "客户品牌" },
    { key: "unit", label: "单位" },
    { key: "quantity", label: "数量", type: "number", required: true },
    { key: "targetUnitPrice", label: "目标单价", type: "money" },
    { key: "currency", label: "币种" },
    { key: "matchedProductCode", label: "匹配产品编码" },
    { key: "productMasterId", label: "产品主档ID" },
    { key: "productModelId", label: "品牌型号ID" },
    { key: "productSpecId", label: "产品规格ID" },
    { key: "matchStatus", label: "匹配状态" },
    { key: "remark", label: "备注", type: "textarea" },
  ],
}, {
  key: "quotations",
  title: "报价单",
  table: "po_quotations",
  primaryKey: "id",
  uniqueKeys: ["quotationNo"],
  navGroup: "客户PO",
  route: "/quotation/list",
  description: "根据客户PO和产品主档编码维护报价单。",
  filters: [
    { key: "keyword", label: "报价单", placeholder: "请输入报价单号、客户或来源PO" },
    { key: "status", label: "状态", type: "select", options: [{ label: "草稿", value: "draft" }, { label: "已确认", value: "confirmed" }] },
  ],
  listFields: [
    { key: "quotationNo", label: "报价单号", sortable: true, filterable: true },
    { key: "customerId", label: "客户", filterable: true },
    { key: "sourcePoNo", label: "来源客户PO" },
    { key: "currency", label: "币种" },
    { key: "totalAmount", label: "报价总额", type: "money" },
    { key: "totalProfit", label: "利润", type: "money" },
    { key: "grossMarginRate", label: "毛利率", type: "percentage" },
    { key: "status", label: "状态", filterable: true },
    { key: "createdByName", label: "创建人" },
    { key: "updatedByName", label: "修改人" },
    { key: "confirmedByName", label: "确认人" },
    { key: "createdAt", label: "创建时间", type: "datetime" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "quotationNo", label: "报价单号", required: true },
    { key: "customerId", label: "客户ID" },
    { key: "contractingUnitId", label: "承接单位ID" },
    { key: "sourcePoId", label: "来源客户PO ID" },
    { key: "sourcePoNo", label: "来源客户PO号" },
    { key: "currency", label: "币种", required: true },
    { key: "totalAmount", label: "报价总额", type: "money" },
    { key: "totalProfit", label: "利润", type: "money" },
    { key: "grossMarginRate", label: "毛利率", type: "percentage" },
    { key: "status", label: "状态", type: "select", required: true, options: [{ label: "草稿", value: "draft" }, { label: "已确认", value: "confirmed" }] },
    { key: "remark", label: "备注", type: "textarea" },
    { key: "createdByUserId", label: "创建人ID", hidden: true },
    { key: "createdByName", label: "创建人", hidden: true },
    { key: "updatedByUserId", label: "修改人ID", hidden: true },
    { key: "updatedByName", label: "修改人", hidden: true },
    { key: "confirmedByUserId", label: "确认人ID", hidden: true },
    { key: "confirmedByName", label: "确认人", hidden: true },
  ],
  defaultSort: "updatedAt DESC",
}, {
  key: "quotation-items",
  title: "报价明细",
  table: "po_quotation_items",
  primaryKey: "id",
  navGroup: "隐藏",
  route: "/quotation/items",
  description: "维护报价单明细和产品主档编码。",
  filters: [{ key: "keyword", label: "报价明细", placeholder: "请输入报价产品编码或名称" }],
  listFields: [
    { key: "quotationId", label: "报价单ID" },
    { key: "lineNo", label: "行号", type: "number" },
    { key: "productCode", label: "产品编码", filterable: true },
    { key: "productName", label: "产品名称" },
    { key: "quantity", label: "数量", type: "number" },
    { key: "unitPrice", label: "单价", type: "money" },
    { key: "amount", label: "金额", type: "money" },
    { key: "currency", label: "币种" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "quotationId", label: "报价单ID", required: true },
    { key: "lineNo", label: "行号", type: "number", required: true },
    { key: "productCode", label: "产品编码", required: true },
    { key: "productName", label: "产品名称", required: true },
    { key: "productMasterId", label: "产品主档ID" },
    { key: "productModelId", label: "品牌型号ID" },
    { key: "productSpecId", label: "产品规格ID" },
    { key: "quantity", label: "数量", type: "number", required: true },
    { key: "unitPrice", label: "单价", type: "money" },
    { key: "amount", label: "金额", type: "money" },
    { key: "currency", label: "币种" },
    { key: "remark", label: "备注", type: "textarea" },
  ],
}, {
  key: "settlement-projects",
  title: "项目结算",
  table: "po_settlement_projects",
  primaryKey: "id",
  navGroup: "客户PO",
  route: "/po/settlement-projects",
  description: "管理已确认报价单的采购执行、成本费用、销售收入、发票和项目结算。",
  filters: [
    { key: "keyword", label: "项目结算", placeholder: "请输入项目单号、报价单号或客户" },
    { key: "status", label: "状态", type: "select", options: [
      { label: "采购中", value: "purchasing" },
      { label: "采购完成", value: "procurement_completed" },
      { label: "验收中", value: "accepting" },
      { label: "已完结", value: "closed" },
    ] },
  ],
  listFields: [
    { key: "projectNo", label: "项目单号", sortable: true, filterable: true },
    { key: "quotationNo", label: "报价单号", sortable: true, filterable: true },
    { key: "customerName", label: "客户", sortable: true, filterable: true },
    { key: "contractingUnitName", label: "承接单位", sortable: true, filterable: true },
    { key: "quotedPurchaseCostUsd", label: "采购成本（未税 USD）", type: "money" },
    { key: "purchasedCostUsd", label: "已采购成本（未税 USD）", type: "money" },
    { key: "quotedSalesRevenueUsd", label: "销售收入（未税 USD）", type: "money" },
    { key: "receivedRevenueTaxIncludedUsd", label: "已销售收入（含税 USD）", type: "money" },
    { key: "receivedRevenueUsd", label: "已销售收入（未税 USD）", type: "money" },
    { key: "grossProfitUsd", label: "项目毛利（未税 USD）", type: "money" },
    { key: "status", label: "状态", sortable: true, filterable: true },
    { key: "createdByName", label: "创建人" },
    { key: "updatedByName", label: "修改人" },
    { key: "confirmedByName", label: "确认人" },
    { key: "createdAt", label: "创建时间", type: "datetime" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
  ],
  formFields: [],
  defaultSort: "createdAt DESC",
}, {
  key: "history-quotations",
  title: "历史报价",
  table: "po_history_quotations",
  primaryKey: "id",
  navGroup: "客户PO",
  route: "/history-quotations",
  description: "按客户和产品编码查询历史报价。",
  filters: [{ key: "keyword", label: "历史报价", placeholder: "请输入客户ID、产品编码或产品名称" }],
  listFields: [
    { key: "quotationDate", label: "报价日期", type: "date", sortable: true },
    { key: "customerId", label: "客户", filterable: true },
    { key: "productCode", label: "产品编码", filterable: true, sortable: true },
    { key: "productName", label: "产品名称" },
    { key: "customerPrice", label: "客户报价", type: "money" },
    { key: "currency", label: "币种" },
    { key: "remark", label: "备注" },
    { key: "createdAt", label: "创建时间", type: "datetime" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "quotationId", label: "报价单ID" },
    { key: "quotationDate", label: "报价日期", type: "date", required: true },
    { key: "customerId", label: "客户ID" },
    { key: "productCode", label: "产品编码", required: true },
    { key: "productName", label: "产品名称", required: true },
    { key: "productMasterId", label: "产品主档ID" },
    { key: "productModelId", label: "品牌型号ID" },
    { key: "productSpecId", label: "产品规格ID" },
    { key: "customerPrice", label: "客户报价", type: "money" },
    { key: "currency", label: "币种" },
    { key: "remark", label: "备注", type: "textarea" },
  ],
  defaultSort: "quotationDate DESC, createdAt DESC",
});

entityConfigs.push({
  key: "product-masters",
  title: "产品主档",
  table: "po_product_masters",
  primaryKey: "id",
  uniqueKeys: ["masterCode"],
  navGroup: "产品管理",
  route: "/product-catalog",
  description: "维护一品一档的产品基础资料，按产品编码排序。",
  filters: [
    { key: "keyword", label: "产品档案", placeholder: "请输入产品编码、名称、规格或品牌" },
  ],
  listFields: [
    { key: "masterCode", label: "产品编码", sortable: true, filterable: true },
    { key: "name", label: "产品名称", sortable: true, filterable: true },
    { key: "nameEn", label: "产品英文名称", sortable: true, filterable: true },
    { key: "specification", label: "规格", sortable: true, filterable: true },
    { key: "brand", label: "品牌", sortable: true, filterable: true },
    { key: "category", label: "品类", sortable: true, filterable: true },
    { key: "unit", label: "单位" },
    { key: "suggestedPurchaseUnitPrice", label: "建议采购价（CNY）", type: "money", sortable: true },
    { key: "length", label: "长（cm）", type: "number" },
    { key: "width", label: "宽（cm）", type: "number" },
    { key: "height", label: "高（cm）", type: "number" },
    { key: "grossWeight", label: "毛重（kg）", type: "number" },
    { key: "hsCodeMx", label: "墨西哥HS编码", sortable: true, filterable: true },
    { key: "needNom", label: "NOM认证", type: "boolean", sortable: true, filterable: true },
    { key: "createdAt", label: "创建时间", type: "datetime", defaultVisible: false },
    { key: "updatedAt", label: "更新时间", type: "datetime", defaultVisible: false },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "masterCode", label: "产品编码", required: true },
    { key: "name", label: "产品名称", required: true },
    { key: "nameEn", label: "产品英文名称" },
    { key: "specification", label: "规格" },
    { key: "brand", label: "品牌" },
    { key: "category", label: "品类", required: true, lookupSource: "product-categories", placeholder: "请选择或输入产品类别" },
    { key: "unit", label: "单位", required: true },
    { key: "suggestedPurchaseUnitPrice", label: "建议采购价（CNY）", type: "money" },
    { key: "length", label: "长（cm）", type: "number" },
    { key: "width", label: "宽（cm）", type: "number" },
    { key: "height", label: "高（cm）", type: "number" },
    { key: "grossWeight", label: "毛重（kg）", type: "number" },
    { key: "hsCodeMx", label: "墨西哥HS编码", readonly: true },
    { key: "needNom", label: "NOM认证", type: "boolean", readonly: true },
  ],
  defaultSort: "masterCode ASC",
}, {
  key: "product-models",
  title: "品牌型号",
  table: "po_product_models",
  primaryKey: "id",
  uniqueKeys: ["modelCode"],
  navGroup: "隐藏",
  route: "/product-catalog/models",
  description: "产品主档下的品牌和型号。",
  filters: [{ key: "keyword", label: "品牌型号", placeholder: "请输入型号编码、品牌或型号" }],
  listFields: [
    { key: "masterId", label: "产品主档ID" },
    { key: "modelCode", label: "品牌型号编码" },
    { key: "brand", label: "品牌" },
    { key: "model", label: "型号" },
    { key: "series", label: "系列" },
    { key: "supplierId", label: "供应商" },
    { key: "purchaseCurrency", label: "采购币种" },
    { key: "suggestedPurchaseUnitPrice", label: "建议采购价", type: "money" },
    { key: "status", label: "状态" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "masterId", label: "产品主档ID", required: true },
    { key: "modelCode", label: "品牌型号编码", required: true },
    { key: "brand", label: "品牌", required: true },
    { key: "model", label: "型号", required: true },
    { key: "series", label: "系列" },
    { key: "supplierId", label: "供应商" },
    { key: "purchaseCurrency", label: "采购币种", required: true },
    { key: "suggestedPurchaseUnitPrice", label: "建议采购价", type: "money" },
    { key: "length", label: "长", type: "number" },
    { key: "width", label: "宽", type: "number" },
    { key: "height", label: "高", type: "number" },
    { key: "grossWeight", label: "毛重", type: "number" },
    { key: "hsCodeCn", label: "中国HS编码" },
    { key: "hsCodeMx", label: "目的地HS编码" },
    { key: "isMagnetic", label: "磁性", type: "boolean" },
    { key: "isElectric", label: "带电", type: "boolean" },
    { key: "needNom", label: "需要NOM", type: "boolean" },
    { key: "status", label: "状态", type: "select", required: true, options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
  ],
  defaultSort: "updatedAt DESC",
}, {
  key: "product-specifications",
  title: "产品规格",
  table: "po_product_specifications",
  primaryKey: "id",
  uniqueKeys: ["specProductCode", "specCode"],
  navGroup: "隐藏",
  route: "/product-catalog/specifications",
  description: "每个品牌型号下的规格与独立产品编码。",
  filters: [{ key: "keyword", label: "产品规格", placeholder: "请输入产品编码、规格编码或名称" }],
  listFields: [
    { key: "modelId", label: "品牌型号ID" },
    { key: "specProductCode", label: "产品编码" },
    { key: "specCode", label: "规格编码" },
    { key: "specKey", label: "规格键" },
    { key: "specName", label: "规格名称" },
    { key: "mode", label: "规格模式" },
    { key: "parameterValue", label: "参数值", type: "number" },
    { key: "parameterUnit", label: "参数单位" },
    { key: "status", label: "状态" },
  ],
  formFields: [
    { key: "id", label: "内部ID", hidden: true },
    { key: "modelId", label: "品牌型号ID", required: true },
    { key: "specProductCode", label: "产品编码", required: true },
    { key: "specCode", label: "规格编码" },
    { key: "specKey", label: "规格键", required: true },
    { key: "specName", label: "规格名称", required: true },
    { key: "mode", label: "规格模式", type: "select", options: [{ label: "固定规格", value: "fixed" }, { label: "参数规格", value: "parameter" }] },
    { key: "parameterValue", label: "参数值", type: "number" },
    { key: "parameterUnit", label: "参数单位" },
    { key: "purchaseCurrency", label: "采购币种", required: true },
    { key: "suggestedPurchaseUnitPrice", label: "建议采购价", type: "money" },
    { key: "length", label: "长", type: "number" },
    { key: "width", label: "宽", type: "number" },
    { key: "height", label: "高", type: "number" },
    { key: "grossWeight", label: "毛重", type: "number" },
    { key: "status", label: "状态", type: "select", required: true, options: [{ label: "启用", value: "active" }, { label: "停用", value: "disabled" }] },
  ],
  defaultSort: "updatedAt DESC",
});

entityConfigs.push(
  {
    key: "product-categories",
    title: "产品类别",
    table: "po_tariff_rates",
    primaryKey: "id",
    uniqueKeys: ["deviceType"],
    navGroup: "产品管理",
    route: "/product-categories",
    description: "维护产品类别与墨西哥HS编码、NOM认证的匹配关系。",
    filters: [{ key: "keyword", label: "产品类别", placeholder: "请输入产品类别或HS编码" }],
    listFields: [
      { key: "deviceType", label: "产品类别", sortable: true, filterable: true },
      { key: "hsCode", label: "墨西哥HS编码", sortable: true, filterable: true },
      { key: "needNom", label: "NOM认证", type: "boolean", sortable: true, filterable: true },
      { key: "remark", label: "备注" },
    ],
    formFields: [
      { key: "id", label: "内部ID", hidden: true },
      { key: "deviceType", label: "产品类别", required: true },
      { key: "hsCode", label: "墨西哥HS编码" },
      { key: "needNom", label: "NOM认证", type: "boolean" },
      { key: "remark", label: "备注", type: "textarea" },
    ],
    defaultSort: "deviceType ASC",
  },
  {
    key: "customer-product-aliases",
    title: "客户产品别名",
    table: "po_customer_product_aliases",
    primaryKey: "id",
    navGroup: "客户PO",
    route: "/customer-product-aliases",
    description: "维护客户侧产品名称、SKU与产品主档编码的匹配关系。",
    filters: [{ key: "keyword", label: "客户产品别名", placeholder: "请输入客户、SKU、客户产品名或产品编码" }],
    listFields: [
      { key: "customerName", label: "客户", filterable: true },
      { key: "customerSku", label: "客户SKU", filterable: true },
      { key: "customerProductName", label: "客户产品名称", filterable: true },
      { key: "customerSpec", label: "客户规格" },
      { key: "productCode", label: "产品主档编码", filterable: true },
      { key: "productName", label: "产品名称" },
      { key: "specificationName", label: "产品规格" },
    ],
    formFields: [
      { key: "id", label: "内部ID", hidden: true },
      { key: "customerId", label: "客户ID", required: true },
      { key: "customerName", label: "客户名称", required: true },
      { key: "customerSku", label: "客户SKU" },
      { key: "customerProductName", label: "客户产品名称", required: true },
      { key: "customerSpec", label: "客户规格" },
      { key: "customerBrand", label: "客户品牌" },
      { key: "productId", label: "产品ID" },
      { key: "productCode", label: "产品主档编码", required: true },
      { key: "productName", label: "产品名称", required: true },
      { key: "productMasterId", label: "产品主档ID" },
      { key: "productModelId", label: "品牌型号ID" },
      { key: "productSpecId", label: "产品规格ID" },
      { key: "specificationKey", label: "规格键" },
      { key: "specificationName", label: "规格名称" },
    ],
    defaultSort: "updatedAt DESC",
  },
  ...[
    ["customer-contacts", "客户联系人", "common_customer_contacts", "contactId", "customerId", "客户"],
    ["customer-bank-accounts", "客户银行账户", "common_customer_bank_accounts", "accountId", "customerId", "客户"],
    ["supplier-contacts", "供应商联系人", "common_supplier_contacts", "contactId", "supplierId", "供应商"],
    ["supplier-bank-accounts", "供应商银行账户", "common_supplier_bank_accounts", "accountId", "supplierId", "供应商"],
    ["undertaking-unit-contacts", "承接单位联系人", "common_undertaking_unit_contacts", "contactId", "undertakingUnitId", "承接单位"],
    ["undertaking-unit-bank-accounts", "承接单位银行账户", "common_undertaking_unit_bank_accounts", "accountId", "undertakingUnitId", "承接单位"],
  ].map(([key, title, table, primaryKey, ownerKey, ownerLabel]) => ({
    key,
    title,
    table,
    primaryKey,
    navGroup: "业务伙伴",
    route: `/master-data/${key}`,
    description: `维护${title}，作为${ownerLabel}公共基础资料的一部分。`,
    filters: [{ key: "keyword", label: title, placeholder: `请输入${ownerLabel}ID、姓名、银行或账号` }],
    listFields: table.endsWith("contacts")
      ? [
          { key: ownerKey, label: `${ownerLabel}ID`, filterable: true },
          { key: "name", label: "姓名", filterable: true },
          { key: "title", label: "职务" },
          { key: "phone", label: "电话" },
          { key: "email", label: "邮箱" },
          { key: "isPrimary", label: "默认联系人", type: "boolean" },
        ]
      : [
          { key: ownerKey, label: `${ownerLabel}ID`, filterable: true },
          { key: "accountName", label: "账户名称", filterable: true },
          { key: "bankName", label: "银行名称" },
          { key: "bankAccount", label: "银行账号" },
          { key: "currency", label: "币种", type: "select", allowCustom: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
          { key: "isDefault", label: "默认账户", type: "boolean" },
        ],
    formFields: table.endsWith("contacts")
      ? [
          { key: primaryKey, label: "内部ID", hidden: true },
          { key: ownerKey, label: `${ownerLabel}ID`, required: true },
          { key: "name", label: "姓名" },
          { key: "title", label: "职务" },
          { key: "phone", label: "电话" },
          { key: "email", label: "邮箱" },
          { key: "isPrimary", label: "默认联系人", type: "boolean" },
        ]
      : [
          { key: primaryKey, label: "内部ID", hidden: true },
          { key: ownerKey, label: `${ownerLabel}ID`, required: true },
          { key: "accountName", label: "账户名称", required: true },
          { key: "bankName", label: "银行名称", required: true },
          { key: "bankAccount", label: "银行账号", required: true },
          { key: "currency", label: "币种", type: "select", allowCustom: true, required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
          { key: "bankRoutingNumber", label: "银行行号" },
          { key: "swiftCode", label: "Swift code" },
          { key: "bankAddress", label: "银行地址", type: "textarea" },
          { key: "isDefault", label: "默认账户", type: "boolean" },
        ],
    defaultSort: "updatedAt DESC",
  } satisfies EntityConfig)),
  {
    key: "huawei-cloud",
    title: "华为云对账",
    table: "cloud_rows",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/cloud/reconciliation",
    description: "华为云月度账单、收款、确认和跨月对账。",
    listFields: [],
    formFields: [],
    filters: [],
  },
  {
    key: "huawei-cloud-mappings",
    title: "华为云服务映射",
    table: "cloud_mappings",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/cloud/mappings",
    description: "维护供应商、承接单位、客户和云账号映射。",
    listFields: [],
    formFields: [],
    filters: [],
  },
  {
    key: "huawei-cloud-supplier-payments",
    title: "华为云供应商付款",
    table: "cloud_supplier_payments",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/cloud/supplier-payments",
    description: "登记华为云供应商付款、发票和付款状态。",
    listFields: [],
    formFields: [],
    filters: [],
  },
);

entityConfigs.push({
  key: "b6-type-configs",
  title: "B6类型规则",
  table: "b6typeconfigs",
  primaryKey: "b6Type",
  navGroup: "隐藏",
  route: "/finance/b6-type-configs",
  description: "维护B6类型的资金占用、备件服务和结算规则；价格版本确认后会保存规则快照。",
  filters: [{ key: "keyword", label: "B6类型", placeholder: "请输入B6类型、别名或适用范围" }],
  listFields: [
    { key: "b6Type", label: "B6类型" },
    { key: "alias", label: "别名" },
    { key: "scope", label: "适用范围" },
    { key: "defaultFundingMonths", label: "资金占用月数", type: "number" },
    { key: "defaultSpareOccupancyMonths", label: "备件占用月数", type: "number" },
    { key: "overseasSpareServiceAvailable", label: "海外备件服务", type: "boolean" },
    { key: "defaultSpareRate", label: "备件费率（%）", type: "percentage" },
    { key: "spareSettlementMethod", label: "备件结算方式" },
    { key: "status", label: "状态" },
    { key: "sortOrder", label: "排序", type: "number" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
  ],
  formFields: [
    { key: "b6Type", label: "B6类型", required: true },
    { key: "alias", label: "别名" },
    { key: "scope", label: "适用范围" },
    { key: "fundingCostIncluded", label: "整机价已含资金占用费", type: "boolean" },
    { key: "spareCostIncluded", label: "整机价已含备件费用", type: "boolean" },
    { key: "defaultFundingMonths", label: "默认资金占用月数", type: "number", placeholder: "留空表示待确认" },
    { key: "defaultSpareOccupancyMonths", label: "默认备件占用月数", type: "number", placeholder: "留空表示待确认" },
    { key: "overseasSpareServiceAvailable", label: "提供海外备件服务", type: "boolean" },
    { key: "defaultSpareRate", label: "默认备件费率（%）", type: "percentage" },
    { key: "spareSettlementMethod", label: "备件结算方式", type: "select", options: [
      { label: "备件单独结差", value: "备件单独结差" },
      { label: "按SL模板费率", value: "按SL模板费率" },
      { label: "整机价已含备件费用", value: "整机价已含备件费用" },
    ] },
    { key: "slPricingInstruction", label: "SL模板计价说明", type: "textarea" },
    { key: "notes", label: "备注", type: "textarea" },
    { key: "status", label: "状态", type: "select", required: true, options: [{ label: "启用", value: "启用" }, { label: "停用", value: "停用" }] },
    { key: "sortOrder", label: "排序", type: "number" },
  ],
  defaultSort: "sortOrder ASC, b6Type ASC",
}, {
  key: "capex-pricing",
  title: "CAPEX/OPEX锚定价格",
  table: "capexpricingversions",
  primaryKey: "versionId",
  navGroup: "隐藏",
  route: "/finance/capex-pricing",
  description: "按国家和价格版本维护CAPEX/OPEX锚定价格、完整计算过程和历史快照。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "balance-settlements",
  title: "实例结差",
  table: "balancesettlements",
  primaryKey: "settlementNo",
  navGroup: "隐藏",
  route: "/finance/balance-settlements",
  description: "基于采购CAPEX/OPEX、结差汇率与已确认锚定价格版本生成实例结差来源单，并统一确认各类结差来源单。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "balance-final-settlements",
  title: "结差结算单",
  table: "balancesettlementfinals",
  primaryKey: "finalSettlementNo",
  navGroup: "隐藏",
  route: "/finance/balance-final-settlements",
  description: "按国家、结差期间和币种汇集已确认的实例结差与非实例费用结差，形成可追溯的最终结差结算单。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "non-instance-settlements",
  title: "非实例费用结差",
  table: "balancesettlements",
  primaryKey: "settlementNo",
  navGroup: "隐藏",
  route: "/finance/non-instance-settlements",
  description: "按备件、清关费、跨境金融税、人力及其他费用类型录入横向明细来源单。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "internal-service-fee-available",
  title: "待初始化内部服务费实例",
  table: "billinginstanceledgers",
  primaryKey: "ledgerId",
  navGroup: "隐藏",
  route: "/finance/internal-service-fee-available",
  description: "显示已有月账单台账但尚未生成内部服务费的实例。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "internal-service-fees",
  title: "内部服务费分摊",
  table: "monthlyinternalservicefees",
  primaryKey: "id",
  navGroup: "隐藏",
  route: "/finance/internal-service-fees",
  description: "按合同未税收入减设备采购总成本进行内部服务费分摊，并支持区间调整和月度归档。",
  filters: [{ key: "keyword", label: "内部服务费", placeholder: "请输入国家、批次、需求单、PO或实例编码" }],
  listFields: [
    { key: "writeOffMonth", label: "核算月份", type: "date" },
    { key: "countryCode", label: "国家" },
    { key: "undertakingUnitCode", label: "承接单位" },
    { key: "supplierCode", label: "供应商" },
    { key: "customerCode", label: "客户" },
    { key: "batchName", label: "批次" },
    { key: "requestNo", label: "需求单号" },
    { key: "poNo", label: "PO单号" },
    { key: "deviceCode", label: "实例编码" },
    { key: "internalServiceFeeAmount", label: "内部服务费（未税）", type: "money" },
    { key: "archived", label: "归档状态" },
  ],
  formFields: [],
}, {
  key: "internal-service-fee-adjustments",
  title: "内部服务费调整单",
  table: "internalservicefeeadjustments",
  primaryKey: "adjustmentNo",
  navGroup: "隐藏",
  route: "/finance/internal-service-fee-adjustments",
  description: "查看和撤销未涉及归档月份的内部服务费区间调整。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "internal-service-fee-snapshots",
  title: "内部服务费归档快照",
  table: "internalservicefeesnapshots",
  primaryKey: "snapshotNo",
  navGroup: "隐藏",
  route: "/finance/internal-service-fee-snapshots",
  description: "查看已归档月份的内部服务费快照及冻结明细。",
  filters: [],
  listFields: [],
  formFields: [],
});

const auditListFields: EntityField[] = [
  { key: "createdAt", label: "创建时间", type: "datetime" },
  { key: "updatedAt", label: "更新时间", type: "datetime" },
];

for (const config of entityConfigs) {
  const existingKeys = new Set(config.listFields.map((field) => field.key));
  config.listFields = [
    ...config.listFields,
    ...auditListFields.filter((field) => !existingKeys.has(field.key)),
  ];
}

const financeChildren: NonNullable<NavGroup["children"]> = [
  {
    title: "成本与锚定价格",
    items: getEntitiesByKeys(["b6-type-configs", "capex-pricing", "balance-settlements", "non-instance-settlements", "balance-final-settlements"]),
  },
  {
    title: "月账单管理",
    items: getEntitiesByKeys(["billing-available", "billing-ledgers", "monthly-billing-writeoffs", "billing-statements"]),
  },
  {
    title: "预付款管理",
    items: getEntitiesByKeys([
      "prepayment-available",
      "prepayment-contracts",
      "monthly-prepayment-writeoffs",
      "prepayment-writeoff-adjustments",
    ]),
  },
  {
    title: "服务费核算",
    items: getEntitiesByKeys([
      "service-fees", "service-fee-snapshots", "service-fee-snapshot-items",
      "internal-service-fee-available", "internal-service-fees", "internal-service-fee-adjustments", "internal-service-fee-snapshots",
    ]),
  },
];

const userManagementChildren: NonNullable<NavGroup["children"]> = [
  {
    title: "功能启用",
    items: [{
      key: "system-module-features",
      title: "功能启用",
      table: "common_modules",
      primaryKey: "moduleKey",
      navGroup: "用户管理",
      route: "/system/module-features",
      description: "管理暂未正式启用的系统功能。",
      adminOnly: true,
      includeInFeatureToggles: false,
      filters: [],
      listFields: [],
      formFields: [],
    }],
  },
  {
    title: "账户管理",
    items: [{
      key: "system-users",
      title: "账户管理",
      table: "common_users",
      primaryKey: "userId",
      navGroup: "用户管理",
      route: "/system/users",
      description: "管理员管理用户账号、启用状态和系统权限。",
      adminOnly: true,
      includeInFeatureToggles: false,
      filters: [],
      listFields: [],
      formFields: [],
    }],
  },
];

const powerChildren: NonNullable<NavGroup["children"]> = [
  { title: "客户需求", items: getEntitiesByKeys(["requests", "request-items"]) },
  { title: "采购管理", items: getEntitiesByKeys(["purchase-orders", "purchase-order-items"]) },
  { title: "合同管理", items: entityConfigs.filter((entity) => entity.navGroup === "合同管理") },
  { title: "物流管理", items: entityConfigs.filter((entity) => entity.navGroup === "物流管理") },
  { title: "财务管理", items: [], children: financeChildren },
  { title: "基础信息", items: entityConfigs.filter((entity) => entity.navGroup === "基础信息") },
  {
    title: "数据工具",
    items: [{
      key: "data-imports",
      title: "数据导入中心",
      table: "power_importjobs",
      primaryKey: "jobId",
      navGroup: "数据工具",
      route: "/data-imports",
      description: "统一管理模板下载、文件上传、导入预览、错误报告和导入历史。",
      filters: [],
      listFields: [],
      formFields: [],
    }],
  },
];

export const navGroups: NavGroup[] = [
  { title: "算力系统", items: [], children: powerChildren },
  {
    title: "集采系统",
    items: [],
    children: [
      { title: "客户PO", items: getEntitiesByKeys(["customer-pos", "quotations", "history-quotations"]) },
      { title: "项目结算", items: getEntitiesByKeys(["settlement-projects"]) },
      { title: "产品管理", items: getEntitiesByKeys(["product-categories", "product-masters"]) },
      { title: "采购管理", items: getEntitiesByKeys(["customer-product-aliases"]) },
    ],
  },
  {
    title: "华为云业务",
    items: [],
    children: [{ title: "华为云对账", items: getEntitiesByKeys(["huawei-cloud"]) }],
  },
  { title: "业务伙伴", items: getEntitiesByKeys(["suppliers", "customers", "undertaking-units"]) },
  { title: "用户管理", items: [], children: userManagementChildren },
];

export function getEntityConfig(key: string): EntityConfig | undefined {
  return entityConfigs.find((entity) => entity.key === key);
}
