import type { FieldType } from "./modules";

export type DemandPlanFieldSpec = {
  key: string;
  label: string;
  type?: FieldType;
  defaultVisible?: boolean;
};

const text = (key: string, label: string, defaultVisible = false): DemandPlanFieldSpec => ({ key, label, defaultVisible });
const number = (key: string, label: string, defaultVisible = false): DemandPlanFieldSpec => ({ key, label, type: "number", defaultVisible });
const time = (key: string, label: string, defaultVisible = false): DemandPlanFieldSpec => ({ key, label, type: "datetime", defaultVisible });

export const purchaseOrderSnFieldSpecs: DemandPlanFieldSpec[] = [
  text("sn", "SN", true),
  text("fixedAssetCode", "固定资产编码", true),
  text("poNo", "PO", true),
  text("materialDescription", "物料描述", true),
  text("shippingBatch", "发货批次", true),
  text("parentAssetNo", "甲方父项固资号", true),
  text("componentCategory", "部件类型", true),
  text("packingListNo", "箱单号", true),
  text("parentCode", "甲方父项编码", true),
  text("finalParentCode", "甲方最终父项编码", true),
  text("level", "层级", true),
  text("supplierFinalParentCode", "供应商最终父项编码", true),
  text("deviceVendor", "设备厂商", true),
  text("childSparePartCode", "子项备件编码", true),
  text("childTopSn", "子项顶部SN", true),
  text("supplierParentSn", "供应商父项SN", true),
  text("supplierChildComponentCode", "供应商子项部件编码", true),
  text("supplierParentCode", "供应商父项编码", true),
  text("customerChildComponentCode", "甲方子项部件编码", true),
  text("customerChildComponentOriginalSn", "甲方子项部件原厂SN", true),
  text("rackUnit", "U位", true),
  text("finalParentSn", "最终父项SN", true),
  text("finalParentPnDescription", "最终父项PN描述", true),
  text("childComponentDescription", "子项部件描述", true),
  text("finalParentPn", "甲方最终父项PN", true),
  text("childComponentOriginalSn", "子项部件原厂SN", true),
  text("rowId", "行id"),
  text("tenantId", "租户id"),
  text("template", "模板"),
  text("version", "版本"),
  text("businessFlowId", "业务流id"),
  text("coreDocument", "是否核心单据"),
  text("processName", "流程名称"),
  text("processVersion", "流程版本"),
  text("upstreamDocumentId", "上游单据主表id"),
  text("upstreamDocumentItemId", "上游单据子表id"),
  text("upstreamDocumentType", "上游单据类型"),
  text("businessFlowInstanceId", "业务流实例id"),
  text("sourceId", "ID"),
  time("timestamp", "时间戳"),
];

export const purchaseOrderPlanFieldSpecs: DemandPlanFieldSpec[] = [
  text("sourcePlanId", "ID", true),
  time("wholeMachineSupplierPoActivatedAt", "整机供应商PO激活时间", true),
  time("quoteReceivedAt", "算力供应商收到CEG报价时间", true),
  time("poIssuedAt", "算力PO下发时间", true),
  time("wholeMachineSupplierPoConfirmedAt", "整机供应商PO确认时间", true),
  time("receiptProofUploadedAt", "签收证明上传时间", true),
  time("logisticsReceivedAt", "物流签收时间", true),
  time("ataAt", "ata时间", true),
  time("ata", "ata", true),
  time("supplierCpd", "供应商反馈cpd", true),
  text("material", "物料", true),
  text("materialName", "物料名称", true),
  number("requestedQuantity", "需求数量", true),
  text("formFactor", "形态", true),
  text("unit", "单位", true),
  text("batch", "批次", true),
  text("sn", "SN", true),
  number("shippedQuantity", "本次发货数量", true),
  text("remark", "备注", true),
  number("pendingShipmentQuantity", "剩余待发货数量", true),
  number("shippedTotalQuantity", "已发货数量", true),
  text("templateIdentifier", "模板标识"),
  text("poStatus", "PO状态"),
  text("rowId", "行ID"),
  text("headerId", "头ID"),
  text("slMaterialCode", "SL物料编码"),
  text("codeDescription", "编码描述"),
  text("modelType", "机型类型"),
  text("productName", "产品名称"),
  text("belongingModelName", "所属机型名称"),
  number("totalModelQuantity", "总机型数量"),
  time("requestedAt", "需求时间"),
  number("matchedQuantity", "已匹配数量"),
  time("supplyDate", "供应日期"),
  text("cabinetNodeCode", "整柜节点编码"),
  text("atpOrder", "ATP内下单"),
  text("orderPriority", "订单优先级"),
  text("datacenterOwner", "机房归属"),
  text("documentNoDescription", "单据号说明"),
  text("computeMode", "算力模式"),
  text("productType", "产品类型"),
  text("category", "类别"),
  text("dataCenter", "数据中心"),
  text("customizationFlag", "定制标识"),
  text("supplyType", "供应类型"),
  text("supplyInformation", "供应信息"),
  time("dssEpd", "DSS_EPD"),
  time("crd", "crd"),
  time("rsd", "rsd"),
  time("rpd", "rpd"),
  time("cpd", "cpd"),
  time("esd", "esd"),
  time("eta", "eta"),
  text("deliveryContact", "收货联系人"),
  text("deliveryContactPhone", "收货联系人电话"),
  text("computeSupplier", "算力供应商"),
  text("country", "国家"),
  text("province", "省份"),
  text("procurementFulfillmentManager", "采购履行经理"),
  text("supplierCode", "供应商编码"),
  text("odmSupplierCodeV", "odm供应商编码-v"),
  text("batchNo", "批次号"),
  text("city", "城市"),
  text("deliveryAddress", "收货地址"),
  text("urgentOrder", "是否急单"),
  text("waybillNo", "运单号"),
  text("logisticsCurrentStatus", "物流当前状态"),
  time("logisticsArrivalTransferAt", "物流到达中转点时间"),
  time("firstDeliveryAt", "首次派送时间"),
  time("apd", "apd"),
  time("asd", "asd"),
  time("computeSupplierInstructionReceivedAt", "算力供应商收到要货指令时间"),
  text("supplierUnsatisfiedExplanation", "供应商不满足说明"),
  text("firstDeliveryFailureReason", "首次派送失败原因"),
  text("productionProgress", "生产进度"),
  time("supplierFeedbackEsd", "供应商反馈esd"),
  time("supplierFeedbackEta", "供应商反馈eta"),
  number("price", "价格"),
  text("purchaseOrderItemRelation", "要货计划子_采购订单子关联"),
  time("apdAt", "apd时间"),
  time("asdAt", "asd时间"),
  time("rsd2", "rsd2"),
  text("transportMode", "运输方式"),
  text("purchaseOrderNo", "采购订单号"),
  number("weight", "重量"),
  number("volume", "体积"),
  number("pieceCount", "件数"),
  time("supplierPoActivatedAt", "供应商po激活时间"),
  text("fulfillmentUnit", "履行单元"),
  text("odmSupplierCode", "odm供应商编码"),
  text("odmSupplierName", "odm供应商名称"),
  text("tenantId", "租户id"),
  text("template", "模板"),
  text("version", "版本"),
  text("businessFlowId", "业务流id"),
  text("coreDocument", "是否核心单据"),
  text("logisticsName", "物流名称"),
  text("processVersion", "流程版本"),
  text("upstreamDocumentItemId", "上游单据字表id"),
  text("upstreamDocumentType", "上游单据类型"),
  text("businessFlowInstanceId", "业务流实际id"),
  time("timestamp", "时间戳"),
  number("originalRequestedQuantity", "原始需求数量"),
];

export function sqlTypeForDemandPlanField(field: DemandPlanFieldSpec) {
  if (field.type === "datetime") return "DATETIME NULL";
  if (field.type === "number") return "DECIMAL(18, 4) NULL";
  if (["sn", "poNo"].includes(field.key)) return "VARCHAR(255) NULL";
  return "TEXT NULL";
}
