"use client";

import { useEffect, useRef, useState } from "react";
import { RefreshCw } from "lucide-react";
import { formatDisplayValue } from "@/lib/display-format";
import { DEFAULT_PAGE_SIZE } from "@/lib/pagination";
import { Button, Panel } from "./ui";
import { PaginationBar } from "./pagination-bar";

type Row = Record<string, string | number | boolean | null>;
const snapshotColumns: Array<[string, string, string?]> = [["snapshotNo", "归档批次号"], ["archiveMonth", "归档月份", "date"], ["countryCode", "国家"], ["itemCount", "明细数", "number"], ["totalAmount", "归档金额", "money"], ["confirmedAt", "归档日期", "date"], ["createdAt", "创建日期", "date"], ["updatedAt", "更新日期", "date"]];
const itemColumns: Array<[string, string, string?]> = [["writeOffMonth", "核算月份", "date"], ["countryCode", "国家"], ["undertakingUnitCode", "承接单位"], ["supplierCode", "供应商"], ["customerCode", "客户"], ["batchName", "批次"], ["requestNo", "需求单号"], ["poNo", "PO单号"], ["deviceCode", "实例编码"], ["currency", "币种"], ["internalServiceFeeAmount", "内部服务费（未税）", "money"], ["sourceType", "来源"], ["adjustmentNo", "调整单号"], ["createdAt", "创建日期", "date"], ["updatedAt", "更新日期", "date"]];

export function InternalServiceFeeSnapshotsPage() {
  const [snapshots, setSnapshots] = useState<Row[]>([]); const [items, setItems] = useState<Row[]>([]); const [selected, setSelected] = useState(""); const [loading, setLoading] = useState(false); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE); const [total, setTotal] = useState(0); const [itemPage, setItemPage] = useState(1); const [itemPageSize, setItemPageSize] = useState(DEFAULT_PAGE_SIZE); const [itemTotal, setItemTotal] = useState(0); const pageSizeRef = useRef(pageSize); const itemPageSizeRef = useRef(itemPageSize);
  async function load(snapshotNo = selected, nextPage = page, nextPageSize = pageSizeRef.current, nextItemPage = itemPage, nextItemPageSize = itemPageSizeRef.current) { setLoading(true); try { const params = new URLSearchParams({ page: String(nextPage), pageSize: String(nextPageSize), itemPage: String(nextItemPage), itemPageSize: String(nextItemPageSize) }); if (snapshotNo) params.set("snapshotNo", snapshotNo); const response = await fetch(`/api/internal-service-fees/snapshots?${params}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "归档快照加载失败"); setSnapshots(data.snapshots ?? []); setItems(data.items ?? []); setTotal(Number(data.total ?? 0)); setPage(Number(data.page ?? nextPage)); setItemTotal(Number(data.itemTotal ?? 0)); setItemPage(Number(data.itemPage ?? nextItemPage)); } catch (error) { alert(error instanceof Error ? error.message : "归档快照加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(""); }, []);
  return <div className="space-y-5"><div><h1 className="text-xl font-medium text-[#303133]">内部服务费归档快照</h1><p className="mt-1 text-sm text-[#909399]">归档后保留当月完整快照，后续合同或人工调整不会改写该批次的明细。</p></div><Panel><div className="flex items-center gap-2 border-b border-[#ebeef5] p-4"><span className="text-sm text-[#606266]">归档批次</span><Button onClick={() => void load()}><RefreshCw size={15} />刷新</Button></div><div className="table-scroll overflow-auto"><table className="w-full min-w-[760px] border-collapse text-sm"><thead className="bg-[#f5f7fa] text-[#303133]"><tr>{snapshotColumns.map(([key, label]) => <th className="whitespace-nowrap border-b border-r border-[#ebeef5] px-3 py-3 text-left font-medium" key={key}>{label}</th>)}</tr></thead><tbody>{snapshots.map((snapshot) => <tr className={`cursor-pointer ${selected === String(snapshot.snapshotNo) ? "bg-[#ecf5ff]" : "hover:bg-[#fafafa]"}`} key={String(snapshot.snapshotNo)} onClick={() => { const snapshotNo = String(snapshot.snapshotNo); setSelected(snapshotNo); setItemPage(1); void load(snapshotNo, page, pageSizeRef.current, 1, itemPageSizeRef.current); }}>{snapshotColumns.map(([key, , type]) => <td className="whitespace-nowrap border-b border-r border-[#ebeef5] px-3 py-3" key={key}>{formatDisplayValue(snapshot[key], type)}</td>)}</tr>)}{!snapshots.length && <tr><td className="py-12 text-center text-[#909399]" colSpan={snapshotColumns.length}>{loading ? "加载中..." : "暂无归档快照"}</td></tr>}</tbody></table></div><PaginationBar page={page} pageSize={pageSize} total={total} onPageChange={(next) => void load(selected, next)} onPageSizeChange={(next) => { pageSizeRef.current = next; setPageSize(next); void load(selected, 1, next); }} /></Panel>{selected && <Panel><div className="border-b border-[#ebeef5] px-4 py-3 text-sm font-medium text-[#303133]">快照明细：{selected}</div><div className="table-scroll overflow-auto"><table className="w-full min-w-[1360px] border-collapse text-sm"><thead className="bg-[#f5f7fa] text-[#303133]"><tr>{itemColumns.map(([key, label]) => <th className="whitespace-nowrap border-b border-r border-[#ebeef5] px-3 py-3 text-left font-medium" key={key}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr className="hover:bg-[#fafafa]" key={String(item.id)}>{itemColumns.map(([key, , type]) => <td className="whitespace-nowrap border-b border-r border-[#ebeef5] px-3 py-3" key={key}>{key === "sourceType" ? (item[key] === "manual" ? "人工区间调整" : "自动分摊") : formatDisplayValue(item[key], type)}</td>)}</tr>)}{!items.length && <tr><td className="py-12 text-center text-[#909399]" colSpan={itemColumns.length}>暂无快照明细</td></tr>}</tbody></table></div><PaginationBar page={itemPage} pageSize={itemPageSize} total={itemTotal} onPageChange={(next) => void load(selected, page, pageSizeRef.current, next)} onPageSizeChange={(next) => { itemPageSizeRef.current = next; setItemPageSize(next); void load(selected, page, pageSizeRef.current, 1, next); }} /></Panel>}</div>;
}
